### ISSUE TITLE
Auto service detection failed with promise

### ISSUE THREAD

**Issue by comtaler** [voltrue2/in-app-purchase#105]
Thanks for the new support for promise. It makes my code a lot cleaner.
But while using the promise version of validate, it gives the following error:
`Error: invalid service given: [object Object]`

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out.
Could you give me the context a bit?
If you could give me the code that fails with the said error, it would be awesome.

Cheers

**Comment by voltrue2** [comment]
Hello

I have fixed the issue with this commit: 4e272964f7ab259f7b35461cde7ed8cce5daf97e

Also I have published npm package version 1.5.1 with the fix.

Cheers
