### ISSUE TITLE
Google rechecks validation even its success

### ISSUE THREAD

**Issue by engineers-bojan** [voltrue2/in-app-purchase#109]
After turning the verbose logs i've noticed that my subscriptions get re-checked even though they were validated successfully?

So the logs go respectively:
[VERBOSE] <Google> Get subscription info from ....
[VERBOSE] <Google> Successfully retrieved subscription info from  ..... and the subscription json data is printed
[VERBOSE] <Google> Validated successfully
[VERBOSE] <Google> Re-check subscription info
[VERBOSE] <Google> Re-check successfully retrieved subscription info: ..... and the subscription json data is printed again...

I guess this shouldnt be happening, there is no need to check the subscription twice in a row? 

I've tried debugging and tracking the flow in the google.js checkSubscriptionStatus method: after getSubsInfo call the "var validate switch" is executed, it enters the "case constants.VALIDATION.SUCCESS:" and calls out the "next(null, constants.VALIDATION.FAILURE)", but immediately afterwards the recheck switch gets executed and it still receivers "constants.VALIDATION.SUCCESS" throught the "state" variable.  

Also wanted to ask you if its possible to add a isGoogleAccessTokenExpired and getGoogleAccessToken methods? I'd like to store my access token in the database and use it when initializing the iap, and since your library already does a lovely job of refreshing my token it would be great if i can just fetch it and place it back in my db :)

**Comment by voltrue2** [comment]
Hello

Thank you for reporting this issue and the suggestion.
I will look into this asap.
Cheers!

**Comment by samuelbwr** [comment]
I also noticed the same behavior.

Any updates on this subject?

**Comment by voltrue2** [comment]
Hello
  

  
This issue has been paused for a while.
  
I’ll have a fresh look at this shortly.
  

  
Cheers
  

  
  

  
  
>

**Comment by liorzam** [comment]
Its happen to me too, so its take longer to complete the validation 
for those who use AWS-Lamda its cost much more money

**Comment by voltrue2** [comment]
Hello
My apologies for taking it long. I have now fixed this issue. The library will recheck the subscription information only when it had to refresh the google token.

The commit: 2ae36705f00f1ad9f6db7163ea9c0196fdbf5381

I will be releasing the new version on npm shortly.

Cheers!

**Comment by voltrue2** [comment]
The version is `1.10.6`

Cheers!
