### ISSUE TITLE
Google's purchaseState coming from wrong object

### ISSUE THREAD

**Issue by gpinkham** [voltrue2/in-app-purchase#112]
I could be wrong but looking at the details of the getSubscription API it does not return a purchaseState field.   It is coming in with the validated Receipt..     I will submit a pull request to move the setting of this in the purchaseData method..

**Comment by voltrue2** [comment]
Hello

The purchaseState in the validated receipt should be the correct property you want to look at.
Since it is validated by either public key or Google server it is the correct state that you can trust.

**Comment by gpinkham** [comment]
maybe the new commits the other day changes the way this works but the purchaseState in the google.js file is getting the purchaseState from the subscription API call not from the validated receipt..   there is no such field in the subscription API..    so when I call validate on a google receipt the purchaseState is always null when the receipt actually has a value.   I will try this out with the new commits and see if it changed..  I'll delete my pull request as I see you already took care of the apple changes..     thanks!
