### ISSUE TITLE
isExpired logic is incorrect

### ISSUE THREAD

**Issue by a-koka** [voltrue2/in-app-purchase#120]
isExpired is incorrectly returning true for subscriptions. Here's a sample of how to handle this for Apple. I'll be researching and updating this with details on how to handle Google subscriptions in a couple days.

```
iap.validate(iapStoreType, iapReceipt, (err, res) => {
  if (!err && iap.isValidated(res)) {
    const purchaseDataList = iap.getPurchaseData(res);
    if(purchaseDataList.length === 1){
      const expiresDate = res.latest_receipt_info ? res.latest_receipt_info.expires_date : 0;
      const isSubscriptionActive = expiresDate > Date.now();
    }
  }
})
```

Happy to provide a PR if you'd like.

PS. Thanks for this awesome lib! 👍

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out. A PR would be a very welcome idea also. I really appreciate it!

Cheers
