### ISSUE TITLE
Update documentation for ignoreExpired

### ISSUE THREAD

**Issue by a-koka** [voltrue2/in-app-purchase#122]
Since the published version now supports `ignoreExpired` on `getPurchaseData`, lets update the documentation. It is confusing the way it reads right now as one section suggests that this flag works on Android vs another suggests that it doesn't.

**Comment by voltrue2** [comment]
Thanks for pointing it out. I'll be updating the doc shortly.

Cheers

**Comment by voltrue2** [comment]
The documentation has been updated. Closing
