### ISSUE TITLE
[google.getPurchaseData] incorrect expirationDate after canceling subscription

### ISSUE THREAD

**Issue by vovkasu** [voltrue2/in-app-purchase#124]
> When the user cancels a subscription, Google Play does not offer a refund for the current billing cycle. Instead, it allows the user to have access to the canceled subscription until the end of the current billing cycle, at which time it terminates the subscription. For example, if a user purchases a monthly subscription and cancels it on the 15th day of the cycle, Google Play will consider the subscription valid until the end of the 30th day (or other day, depending on the month).
https://developer.android.com/google/play/billing/billing_subscriptions.html#cancellation

iap.validate return response like:

```javascript
{ orderId: 'GPA.3383-...',
  packageName: 'com...',
  productId: 'sub_yearly_...',
  purchaseTime: 1503937487252,
  purchaseState: undefined,
  purchaseToken: 'dch...',
  autoRenewing: false,
  status: 0,
  kind: 'androidpublisher#subscriptionPurchase',
  startTimeMillis: '1503937487252',
  expiryTimeMillis: '1536078239352',
  priceCurrencyCode: 'USD',
  priceAmountMicros: '4...',
  countryCode: 'US',
  developerPayload: '',
  paymentState: 1,
  cancelReason: 0,
  userCancellationTimeMillis: '1504669868000',
  service: 'google',
  expirationTime: '1536078239352' }

```

```javascript
let purchaseData = iap.getPurchaseData(response); 
//purchaseData[0].expirationDate == 1504669868000, but need 1536078239352
```

[lib/google.js: ](https://github.com/voltrue2/in-app-purchase/blob/develop/lib/google.js#L472)
```javascript
module.exports.getPurchaseData = function (purchase, options) {
//...
	var data = [];
	var purchaseInfo = responseData.parse(purchase);
//...
	if (purchase.expiryTimeMillis) {
		purchaseInfo.expirationDate = purchase.expiryTimeMillis;
	}
	if (purchase.userCancellationTimeMillis) {  //expirationDate != userCancellationTimeMillis
		purchaseInfo.expirationDate = purchase.userCancellationTimeMillis; 
	}

	data.push(purchaseInfo);
	return data;
};
```

**Comment by vovkasu** [comment]
> Customers may cancel a subscription in the middle of a subscription period, but the subscription remains paid through the end of the same period.
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html

**Comment by voltrue2** [comment]
Hello @vovkasu 

Thank you for reaching out.
Let me look into this ASAP.

Cheers!

**Comment by voltrue2** [comment]
Here is the fix for this: ff6c26545e04b08fbd734c5f2c25d078308a2ef8

**Comment by vovkasu** [comment]
Hello @voltrue2 
I think need delete
lib/google.js lines 502-507.

**Comment by vovkasu** [comment]
Expiration date has nothing to do with the cancellation date. So, the expiration date should never be assigned to cancellation date. Thus, the lines 502-507 in the lib/google.js should be deleted and 
the lines 270-272 in the lib/apple.js.
Customers may cancel a subscription in the middle of a subscription period, but the subscription remains paid through the end of the same period.

**Comment by voltrue2** [comment]
I see. Thank you. I will make the necessary changes.

Cheers

**Comment by voltrue2** [comment]
febedd4a055cb7bf8f07aac48e1b7adbfc3529b0

**Comment by vovkasu** [comment]
Thanks for fixing it so quickly!

**Comment by voltrue2** [comment]
Thank you for helping out!

**Comment by jbgomez21** [comment]
Hi @voltrue2, @vovkasu

This changed was done for  lib/google.js but not in lib/apple.js, that is right?

```
function getSubscriptionExpireDate(data) {
	if (!data) {
		return 0;
	}
	if (data[REC_KEYS.CANCELLATION_DATE] && data[REC_KEYS.EXPIRES_DATE] !== data[REC_KEYS.CANCELLATION_DATE]) {
		return data[REC_KEYS.CANCELLATION_DATE];
	}
	if (data[REC_KEYS.EXPIRES_DATE_MS]) {
		return parseInt(data[REC_KEYS.EXPIRES_DATE_MS], 10);
	}
	if (data[REC_KEYS.EXPIRES_DATE]) {
		return data[REC_KEYS.EXPIRES_DATE];
	}
	if (data[REC_KEYS.EXPIRATION_DATE]) {
		return data[REC_KEYS.EXPIRATION_DATE];
	}
	if (data[REC_KEYS.EXPIRATION_INTENT]) {
		return parseInt(data[REC_KEYS.EXPIRATION_INTENT], 10);
	}
	return 0;
}
```

The next lines should be deleted?

```
	if (data[REC_KEYS.CANCELLATION_DATE] && data[REC_KEYS.EXPIRES_DATE] !== data[REC_KEYS.CANCELLATION_DATE]) {
		return data[REC_KEYS.CANCELLATION_DATE];
	}
```
