### ISSUE TITLE
Not able to get 2 instances of in-app-purchase library with 2 different config.

### ISSUE THREAD

**Issue by ankit-iiita2006** [voltrue2/in-app-purchase#125]
We want to create 2 instances of a in app purchase library with different google, apple configs
Problem is that library has exposed functions at top level and it requires another files(ex:- google.js, apple.js e.t.c) 
and call its functions and sets the relevant config at that level as a result we are only getting singleton.
And not able to initialize 2 separate handlers for 2 different tenant.

Can we please associate config for different libraries like google, apple e.t.c, with their `this` . 
And instance of doing `module.export` of these function, export the new instance with the passed config ?

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out.
Actually this is the whole point of this library that you get to use the same APIs to validate all types of receipts.
Would you please explain the reason for wanting to have 2 or more independent instances of this library in your application?

I am assuming that you mean to do something like this:

var googleValidator = iap.create(googleConf);
var appleValidator = iap.create(appleConfig);

Cheers

**Comment by ankit-iiita2006** [comment]
Thanks for the quick reply, I infact want to use default methods exposed by library and do not want to use `google.js` or `apple.js` separately
what I am trying to do here is pass 2 different configs of my 2 different apps(these are 2 different apps on both android and ios), 
and start 2 different instance of the library and export that, when I initially start my node server, 
my server will then pick the correct IAPHandler of the app, depending on the app from which I am getting validation request.
Below is the code snippet as a work around for this :-

```
const IAPApp1Config      = require('../../../third_party/in-app-purchase2') ;
const IAPApp2Config      = require('../../../third_party/in-app-purchase3') ;

function IAPHandler(MyAppConfig, IAP) {
  this.config = MyAppConfig;
  IAP.config({
    googlePublicKeyStrSandbox: MyAppConfig.IAP.googlePublicKeyStrSandbox,
    googlePublicKeyStrLive: MyAppConfig.IAP.googlePublicKeyStrLive,
    googleRefToken: MyAppConfig.IAP.googleRefToken,
    googleClientID: MyAppConfig.IAP.googleClientID,
    googleClientSecret: MyAppConfig.IAP.googleClientSecret,
    applePassword: MyAppConfig.IAP.applePassword,
    requestDefaults: {
      timeout: MyAppConfig.IAP.request_timeout
    },
    verbose: MyAppConfig.IAP.is_verbose
  });

  IAP.setup(function(err) {
    if (err) {
      
    } else {
      
    }
  });

  this.IAP = IAP;
}  


module.exports = {
  IAPApp1   : new IAPHandler(get_config.getConfigObjects.app1, IAPApp1Config)
  , IAPApp2 : new IAPHandler(get_config.getConfigObjects.app2, IAPApp2Config)  
}
```
Ideally I should not have to require 2 instances of library, but require just 1 instance
and call the constructor function of that and pass the config to get different instance of in-app-purchase handler.
If the `config` present in `google.js`, `apple.js` e.t.c can be associated with the instance of the object, this will be solved.
Right now `https://github.com/voltrue2/in-app-purchase/blob/develop/index.js` when you require `var google = require('./lib/google');`
you are making in singleton, and I am not able to pass 2 different configs and create 2 different instances of it.

**Comment by voltrue2** [comment]
If that is what you want to do then, please use `.validateOnce(...)`. This method is meant for exactly what you are trying to do.

You may pass different configurations per validation with this method.

Cheers

**Comment by ankit-iiita2006** [comment]
Thanks will try that.

Cheers!
