### ISSUE TITLE
iap.isValidated(googleRes) returns true for invalid purchase.

### ISSUE THREAD

**Issue by ravishankar82** [voltrue2/in-app-purchase#127]
Getting following google response in iap.validate
{"orderId":"8558592886143042565.4969504526705069","packageName":"test_product_name","productId":"test_product_id","purchaseTime":1505899993196,"purchaseState":0,"purchaseToken":"pdvwifahusfabujzwcyxiyij","status":0,"error":{"errors":[{"domain":"global","reason":"invalid","message":"Invalid Value"}],"code":400,"message":"Invalid Value"},"service":"google"}

This is invalid purchase because there are error present in response but iap.isValidated(googleRes) returns true. iap npm checks only status == 0

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out. I'll be looking into it.

Cheers

**Comment by voltrue2** [comment]
Here is the fix: 833eade8d16d3fe82c808f6d621e8c5333f166a5

**Comment by voltrue2** [comment]
Closing as it has been resolved
