### ISSUE TITLE
Add a method to tell if a recurring subscription is expired

### ISSUE THREAD

**Issue by reidmweber** [voltrue2/in-app-purchase#13]
I'm only working with Apple right now and I'm going to look through the purchase data and check for any subscriptions that are still valid using the expire_date_ms.

**Comment by voltrue2** [comment]
Thanks for the request. Sorry I couldn't get back sooner. 
I will look into this.

Cheers

**Comment by voltrue2** [comment]
Hi I implemented what I think you have requested for.

Here is the commit: https://github.com/voltrue2/in-app-purchase/commit/121d18f6989cc46c88e0ae0baf99a6b046dd4515

The commit does contain other code that I am working on but if you could look at .isExpired and .getPurchaseData(), you will find that I have added expiration handling.

Let me know what you think.

Cheers
