### ISSUE TITLE
Upgrade dependency "request"

### ISSUE THREAD

**Issue by mobidev111** [voltrue2/in-app-purchase#133]
please upgrade the dependencies

"request": "2.81.0"
->
"request": "2.83.0"

request version 2.81.0 requires an old version of ajv causing peer dependency issues

```
├─┬ in-app-purchase@1.8.2
│ └─┬ request@2.81.0
│   └─┬ har-validator@4.2.1
│     └── ajv@4.11.8 
```

**Comment by voltrue2** [comment]
Hello

Thank you for pointing it out. It's done! `v1.8.4` please.

Cheers
