### ISSUE TITLE
Does this library work for the Mac App Store?

### ISSUE THREAD

**Issue by holgersindbaek** [voltrue2/in-app-purchase#134]
I'm trying to implement in-app purchases for my Mac App Store app which is build with Electron. 

It's not clear to me whether this library will work for a Mac App or whether it only works for iOS?

It's also not clear to me whether this library only does receipt validation or whether it also does the actual in-app purchase?

**Comment by voltrue2** [comment]
Hello 

I might have answers your question in my previous response just now but the library is intended to be used for receipt validation and it does not provide client-side SDK.

Cheers

**Comment by holgersindbaek** [comment]
I've created a post on Stackoverflow with a 300 reputation points worth of bounty. If you think you can get more specific with how you'd do in app purchases, please let me know in there:

https://stackoverflow.com/questions/46753835/implementing-in-app-purchase-in-an-electron-app-for-the-mac-app-store

**Comment by kevinEsherick** [comment]
I think it would be good to clarify in the documentation that this library handles only receipt validation. The name and description make it seem otherwise.

**Comment by voltrue2** [comment]
Hello
  

  
Thank you for pointing it out! I’ll make sure to mention this in the doc!
  

  
Cheers
  

  
  

  
  
>
