### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by igorescobar** [voltrue2/in-app-purchase#135]
Guys,

Would be highly appreciated if you could keep a `CHANGELOG.md` file. We are using this package for quite awhile now and it's hard to see what changed between releases, like this one:
https://github.com/facebook/react/blob/master/CHANGELOG.md

I personally use this gem: 
https://github.com/kawamanza/step-up

This gem helps me to keep to keep this up to date:
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/CHANGELOG.md

Thanks a bunch!

**Comment by voltrue2** [comment]
Hello

Thank you for the suggestion. I must be honest on this point that I have been lazy about it, but you are right.
I’ll add a change log in the near future.

Cheers

**Comment by igorescobar** [comment]
Hey @voltrue2!

No problem! And I appreciate all the work you've done here for us!

Cheers!
