### ISSUE TITLE
Creating test receipts for, well, testing

### ISSUE THREAD

**Issue by fictorial** [voltrue2/in-app-purchase#136]
Hi, thanks for the module!

I see that the [bundled receipt](https://github.com/voltrue2/in-app-purchase/blob/06fb981dae6a5e72febdea7e6abf2f54a8002bf3/test/receipts/apple#L1-L46) uses `com.mindmobapp.download` which I can of include in my own tests.  

Is there a way to create test/fake receipts (say, for Apple or more) with a preconfigured product id for testing?  How did you create the bundled receipt in your tests?

```
$ make aptest

...

[1508255148163][VERBOSE] <Apple> Sandbox validation successful: { receipt: 
   { original_purchase_date_pst: '2012-04-30 08:05:55 America/Los_Angeles',
     original_transaction_id: '1000000046178817',
     original_purchase_date_ms: '1335798355868',
     transaction_id: '1000000046178817',
     quantity: '1',
     product_id: 'com.mindmobapp.download',
     bvrs: '20120427',
     purchase_date_ms: '1335798355868',
     purchase_date: '2012-04-30 15:05:55 Etc/GMT',
     original_purchase_date: '2012-04-30 15:05:55 Etc/GMT',
     purchase_date_pst: '2012-04-30 08:05:55 America/Los_Angeles',
     bid: 'com.mindmobapp.MindMob',
     item_id: '521129812' },
  status: 0 }

```

**Comment by voltrue2** [comment]
Hello 

Unfortunately there’re no way (as far as I know of though) to create fake receipts for any platform.
For iOS you may use sandbox and that is as close as it gets.

Cheers

**Comment by voltrue2** [comment]
Closing
