### ISSUE TITLE
Samsung store support?

### ISSUE THREAD

**Issue by Suvitruf** [voltrue2/in-app-purchase#139]
Any plans to support [Samsung store IAPs](http://developer.samsung.com/iap/guide)?

**Comment by voltrue2** [comment]
Hello

I’m not planning on implementing Samsung store at the moment. 
I wonder if there’s enough needs for it to be worthwhile?

Cheers

**Comment by Suvitruf** [comment]
Not sure. But we are planing to implement Samsung store soon for our game. If we do it using node.js, I will probably create pull request.

**Comment by voltrue2** [comment]
Hello

> If we do it using node.js, I will probably create pull request.
That would be great!

Cheers

**Comment by voltrue2** [comment]
Closing
