### ISSUE TITLE
Add support for "exclude-old-transactions" field for itunes receipt

### ISSUE THREAD

**Issue by zolikobol** [voltrue2/in-app-purchase#143]
Hi, currently the module does not allow us to use "exclude-old-transactions" field to get back only the last transaction. Often we have users for couple of years and the receipt is too big and it takes much more time to response to a request.

Thanks, Zoli.

**Comment by voltrue2** [comment]
Hello

I think it makes sense to implement that into the package. 
I’ll try to get it done as soon as I have the chance.
Thanks for the suggestion!

Cheers

**Comment by zolikobol** [comment]
Hi, thanks.
If it helps, I already have it locally because what I wrote above, so I can create a PR. It is just two line.

Thanks, Zoli.

**Comment by voltrue2** [comment]
Hello

That would be really awesome!
Would you mind sending a PR?

Cheers

**Comment by voltrue2** [comment]
2ee975ce7929280a39d8f1f67fe0af500249f363
