### ISSUE TITLE
What's about "Error: invalid service given: undefined" Error ? 

### ISSUE THREAD

**Issue by ntlzz93** [voltrue2/in-app-purchase#144]
Can Anyone explain this error?

**"Error: invalid service given: undefined"** when I validate receipt apple

**Comment by voltrue2** [comment]
It means you’re passing undefined value to .validate(). If you’re passing a service such as APPLE, GOOGLE etc

**Comment by ntlzz93** [comment]
Thank you
On Dec 13, 2017, at 6:16 PM, Nobuyori Takahashi <notifications@github.com<mailto:notifications@github.com>> wrote:


It means you’re passing undefined value to .validate(). If you’re passing a service such as APPLE, GOOGLE etc
