### ISSUE TITLE
Google validation: bug when try to validate Sbx after Live fail

### ISSUE THREAD

**Issue by karim73** [voltrue2/in-app-purchase#149]
Hi,

Env: Google play store
Validation: Live and sbx (config.test = false)

When i try to validate a receipt, (Live first, then SBX) i got the following error: receipt.data must be a string
Because the receipt.data was parsed in the Live validation step
I just added receipt.data = JSON.stringify(receipt.data) juste before trying sbx validation.

Is there any fix to resolve this issue ?

Thank you

**Comment by voltrue2** [comment]
Hello

There maybe a bug. The sandbox should behave the same way as live. Let me look into this.

Thank you for reporting the issue.

Cheers

**Comment by voltrue2** [comment]
640104ab0db7ea8673464a0a99db7808a483c87e
