### ISSUE TITLE
How to deal with subscriptions?

### ISSUE THREAD

**Issue by liuzhen2008** [voltrue2/in-app-purchase#156]
As far as I know, when key event occur during a subscription life cycle, an event will be received by the client side.

Does that mean all I need to do on the server side is to call iap.validate('GOOGLE'/'APPLE', receipt) and consume the event like that?

On google and apple, they both have a server-to-server notifications. Does this module have configurations to connect to it? If not, I guess I have to resort back to having client app to send me updates?

Thanks

**Comment by superandrew213** [comment]
You can use `in-app-purchase` to handle real time server notifications from Apple.

For Google you need to make some small adjustments. See the issue that I opened [here](https://github.com/voltrue2/in-app-purchase/issues/141) & my [PR](https://github.com/voltrue2/in-app-purchase/pull/142) that makes it easy to handle Google real time server notifications.

@voltrue2 have you had any time to review this. I have been using it for while and haven't had any issues so far.

**Comment by liuzhen2008** [comment]
@superandrew213 This is so cool. Do you know how I would correlate the receipt data with my in app user id? 

I suppose my client still needs to send me something?

Could you point me to the code that I need to write to receive APPLE server-to-server notifications? I couldn't find it in the tutorials..

**Comment by liuzhen2008** [comment]
@superandrew213 @voltrue2  

If i use iap.verify() to verify a subscription receipt from client.

How can I tell if the client doing a "INITIAL_BUY" or "CANCEL" or "RENEWAL"? Do i basically need to infer CANCEL based on whether expirationDate exists or not?

And I have to infer RENEWAL and INITIAL_BUY based on my own backend logic?
