### ISSUE TITLE
Getting duplicated transactions calling iap.getPurchaseData?

### ISSUE THREAD

**Issue by liuzhen2008** [voltrue2/in-app-purchase#159]
```
    iap.setup(function() {
      iap.validate(iap.APPLE, receipt, function(error, data) {
        console.log("Data transaction id");
        for (var i = 0; i < data.latest_receipt_info.length; i ++) {
          console.log(data.latest_receipt_info[i].transaction_id);
        }
        var purchases = iap.getPurchaseData(data);
        console.log("get purchases data transaction id");
        for (var j = 0; j < purchases.length; j ++) {
          console.log(purchases[j].transactionId);
        }

        res.ok();
      });
    })

```
WIth the receipt provided below, I get the following console logs

Data transaction id
1000000381600687
1000000381600903
1000000381601336
1000000381601740
1000000381602052
1000000381602343

get purchases data transaction id
1000000381600903
1000000381601740
1000000381600903
1000000381601740
1000000381602343

is it expect for me to get duplicated purchase data transaction ids? What does it mean when they are duplicated?

**Comment by liuzhen2008** [comment]
below is the receipt string.

`MIIYcQYJKoZIhvcNAQcCoIIYYjCCGF4CAQExCzAJBgUrDgMCGgUAMIIIEgYJKoZIhvcNAQcBoIIIAwSCB/8xggf7MAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgELAgEBBAMCAQAwCwIBDwIBAQQDAgEAMAsCARACAQEEAwIBADALAgEZAgEBBAMCAQMwDAIBCgIBAQQEFgI0KzAMAgEOAgEBBAQCAgCiMA0CAQMCAQEEBQwDMTAwMA0CAQ0CAQEEBQIDAa4WMA0CARMCAQEEBQwDMS4wMA4CAQkCAQEEBgIEUDI1MDAYAgEEAgECBBAFl5XR+Zv6qOy6rT4XLdKrMBoCAQICAQEEEgwQbG92ZS50aGVjb3ZlLmFwcDAbAgEAAgEBBBMMEVByb2R1Y3Rpb25TYW5kYm94MBwCAQUCAQEEFHQ2E76+3QSHZNZbEMkUM+slixdnMB4CAQwCAQEEFhYUMjAxOC0wMy0wOFQyMDoxNjozMFowHgIBEgIBAQQWFhQyMDEzLTA4LTAxVDA3OjAwOjAwWjBJAgEHAgEBBEFPTShYdSJV/mGB1RaVLBSGenfm06qJzgrPSHuN1HEaPdQyCfKS2j9RzTxHuVHsM18FxzfgjsgMazNOZEPfSPEa+jBLAgEGAgEBBEM737RxtZzhaLeDTGUJ9Bvfl7U5W3/dEddko+DsgusyAv5MUPzw7CY36Y5jzctDKTieijNB8M1ilIZR3JDWHKNyly4kMIIBfAIBEQIBAQSCAXIxggFuMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+pwsxITAaAgIGpgIBAQQRDA9iYXNpY21lbWJlcnNoaXAwGwICBqcCAQEEEgwQMTAwMDAwMDM4MTYwMDY4NzAbAgIGqQIBAQQSDBAxMDAwMDAwMzgxNjAwNjg3MB8CAgaoAgEBBBYWFDIwMTgtMDMtMDhUMTk6NTg6NTVaMB8CAgaqAgEBBBYWFDIwMTgtMDMtMDhUMTk6NTg6NTZaMB8CAgasAgEBBBYWFDIwMTgtMDMtMDhUMjA6MDM6NTVaMIIBfAIBEQIBAQSCAXIxggFuMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+pwsxIjAaAgIGpgIBAQQRDA9iYXNpY21lbWJlcnNoaXAwGwICBqcCAQEEEgwQMTAwMDAwMDM4MTYwMDkwMzAbAgIGqQIBAQQSDBAxMDAwMDAwMzgxNjAwNjg3MB8CAgaoAgEBBBYWFDIwMTgtMDMtMDhUMjA6MDM6NTVaMB8CAgaqAgEBBBYWFDIwMTgtMDMtMDhUMTk6NTg6NTZaMB8CAgasAgEBBBYWFDIwMTgtMDMtMDhUMjA6MDg6NTVaMIIBfAIBEQIBAQSCAXIxggFuMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+pwsxSDAaAgIGpgIBAQQRDA9iYXNpY21lbWJlcnNoaXAwGwICBqcCAQEEEgwQMTAwMDAwMDM4MTYwMTMzNjAbAgIGqQIBAQQSDBAxMDAwMDAwMzgxNjAwNjg3MB8CAgaoAgEBBBYWFDIwMTgtMDMtMDhUMjA6MDk6MTVaMB8CAgaqAgEBBBYWFDIwMTgtMDMtMDhUMTk6NTg6NTZaMB8CAgasAgEBBBYWFDIwMTgtMDMtMDhUMjA6MTQ6MTVaMIIBfAIBEQIBAQSCAXIxggFuMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+pwsxeDAaAgIGpgIBAQQRDA9iYXNpY21lbWJlcnNoaXAwGwICBqcCAQEEEgwQMTAwMDAwMDM4MTYwMTc0MDAbAgIGqQIBAQQSDBAxMDAwMDAwMzgxNjAwNjg3MB8CAgaoAgEBBBYWFDIwMTgtMDMtMDhUMjA6MTQ6MzBaMB8CAgaqAgEBBBYWFDIwMTgtMDMtMDhUMTk6NTg6NTZaMB8CAgasAgEBBBYWFDIwMTgtMDMtMDhUMjA6MTk6MzBaoIIOZTCCBXwwggRkoAMCAQICCA7rV4fnngmNMA0GCSqGSIb3DQEBBQUAMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE1MTExMzAyMTUwOVoXDTIzMDIwNzIxNDg0N1owgYkxNzA1BgNVBAMMLk1hYyBBcHAgU3RvcmUgYW5kIGlUdW5lcyBTdG9yZSBSZWNlaXB0IFNpZ25pbmcxLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKXPgf0looFb1oftI9ozHI7iI8ClxCbLPcaf7EoNVYb/pALXl8o5VG19f7JUGJ3ELFJxjmR7gs6JuknWCOW0iHHPP1tGLsbEHbgDqViiBD4heNXbt9COEo2DTFsqaDeTwvK9HsTSoQxKWFKrEuPt3R+YFZA1LcLMEsqNSIH3WHhUa+iMMTYfSgYMR1TzN5C4spKJfV+khUrhwJzguqS7gpdj9CuTwf0+b8rB9Typj1IawCUKdg7e/pn+/8Jr9VterHNRSQhWicxDkMyOgQLQoJe2XLGhaWmHkBBoJiY5uB0Qc7AKXcVz0N92O9gt2Yge4+wHz+KO0NP6JlWB7+IDSSMCAwEAAaOCAdcwggHTMD8GCCsGAQUFBwEBBDMwMTAvBggrBgEFBQcwAYYjaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy13d2RyMDQwHQYDVR0OBBYEFJGknPzEdrefoIr0TfWPNl3tKwSFMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUiCcXCam2GGCL7Ou69kdZxVJUo7cwggEeBgNVHSAEggEVMIIBETCCAQ0GCiqGSIb3Y2QFBgEwgf4wgcMGCCsGAQUFBwICMIG2DIGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wNgYIKwYBBQUHAgEWKmh0dHA6Ly93d3cuYXBwbGUuY29tL2NlcnRpZmljYXRlYXV0aG9yaXR5LzAOBgNVHQ8BAf8EBAMCB4AwEAYKKoZIhvdjZAYLAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAA2mG9MuPeNbKwduQpZs0+iMQzCCX+Bc0Y2+vQ+9GvwlktuMhcOAWd/j4tcuBRSsDdu2uP78NS58y60Xa45/H+R3ubFnlbQTXqYZhnb4WiCV52OMD3P86O3GH66Z+GVIXKDgKDrAEDctuaAEOR9zucgF/fLefxoqKm4rAfygIFzZ630npjP49ZjgvkTbsUxn/G4KT8niBqjSl/OnjmtRolqEdWXRFgRi48Ff9Qipz2jZkgDJwYyz+I0AZLpYYMB8r491ymm5WyrWHWhumEL1TKc3GZvMOxx6GUPzo22/SGAGDDaSK+zeGLUR2i0j0I78oGmcFxuegHs5R0UwYS/HE6gwggQiMIIDCqADAgECAggB3rzEOW2gEDANBgkqhkiG9w0BAQUFADBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMTMwMjA3MjE0ODQ3WhcNMjMwMjA3MjE0ODQ3WjCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMo4VKbLVqrIJDlI6Yzu7F+4fyaRvDRTes58Y4Bhd2RepQcjtjn+UC0VVlhwLX7EbsFKhT4v8N6EGqFXya97GP9q+hUSSRUIGayq2yoy7ZZjaFIVPYyK7L9rGJXgA6wBfZcFZ84OhZU3au0Jtq5nzVFkn8Zc0bxXbmc1gHY2pIeBbjiP2CsVTnsl2Fq/ToPBjdKT1RpxtWCcnTNOVfkSWAyGuBYNweV3RY1QSLorLeSUheHoxJ3GaKWwo/xnfnC6AllLd0KRObn1zeFM78A7SIym5SFd/Wpqu6cWNWDS5q3zRinJ6MOL6XnAamFnFbLw/eVovGJfbs+Z3e8bY/6SZasCAwEAAaOBpjCBozAdBgNVHQ4EFgQUiCcXCam2GGCL7Ou69kdZxVJUo7cwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAuBgNVHR8EJzAlMCOgIaAfhh1odHRwOi8vY3JsLmFwcGxlLmNvbS9yb290LmNybDAOBgNVHQ8BAf8EBAMCAYYwEAYKKoZIhvdjZAYCAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAE/P71m+LPWybC+P7hOHMugFNahui33JaQy52Re8dyzUZ+L9mm06WVzfgwG9sq4qYXKxr83DRTCPo4MNzh1HtPGTiqN0m6TDmHKHOz6vRQuSVLkyu5AYU2sKThC22R1QbCGAColOV4xrWzw9pv3e9w0jHQtKJoc/upGSTKQZEhltV/V6WId7aIrkhoxK6+JJFKql3VUAqa67SzCu4aCxvCmA5gl35b40ogHKf9ziCuY7uLvsumKV8wVjQYLNDzsdTJWk26v5yZXpT+RN5yaZgem8+bQp0gF6ZuEujPYhisX4eOGBrr/TkJ2prfOv/TgalmcwHFGlXOxxioK0bA8MFR8wggS7MIIDo6ADAgECAgECMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0wNjA0MjUyMTQwMzZaFw0zNTAyMDkyMTQwMzZaMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOSRqQkfkdseR1DrBe1eeYQt6zaiV0xV7IsZid75S2z1B6siMALoGD74UAnTf0GomPnRymacJGsR0KO75Bsqwx+VnnoMpEeLW9QWNzPLxA9NzhRp0ckZcvVdDtV/X5vyJQO6VY9NXQ3xZDUjFUsVWR2zlPf2nJ7PULrBWFBnjwi0IPfLrCwgb3C2PwEwjLdDzw+dPfMrSSgayP7OtbkO2V4c1ss9tTqt9A8OAJILsSEWLnTVPA3bYharo3GSR1NVwa8vQbP4++NwzeajTEV+H0xrUJZBicR0YgsQg0GHM4qBsTBY7FoEMoxos48d3mVz/2deZbxJ2HafMxRloXeUyS0CAwEAAaOCAXowggF2MA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjCCAREGA1UdIASCAQgwggEEMIIBAAYJKoZIhvdjZAUBMIHyMCoGCCsGAQUFBwIBFh5odHRwczovL3d3dy5hcHBsZS5jb20vYXBwbGVjYS8wgcMGCCsGAQUFBwICMIG2GoGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wDQYJKoZIhvcNAQEFBQADggEBAFw2mUwteLftjJvc83eb8nbSdzBPwR+Fg4UbmT1HN/Kpm0COLNSxkBLYvvRzm+7SZA/LeU802KI++Xj/a8gH7H05g4tTINM4xLG/mk8Ka/8r/FmnBQl8F0BWER5007eLIztHo9VvJOLr0bdw3w9F4SfK8W147ee1Fxeo3H4iNcol1dkP1mvUoiQjEfehrI9zgWDGG1sJL5Ky+ERI8GA4nhX1PSZnIIozavcNgs/e66Mv+VNqW2TAYzN39zoHLFbr2g8hDtq6cxlPtdk2f8GHVdmnmbkyQvvY1XGefqFStxu9k0IkEirHDx22TZxeY8hLgBdQqorV2uT80AkHN7B1dSExggHLMIIBxwIBATCBozCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eQIIDutXh+eeCY0wCQYFKw4DAhoFADANBgkqhkiG9w0BAQEFAASCAQBi2jtd7yzoxqUaZIvvbsySVC9kgdTGYm9yiYt/02zi+hdhPv2BxRpy1u2vWQPl3rCXiGx6wvInjT4X4nIn/MdyM4YAqR9wTOEOO0exX7bcQQBEb9LOlqSqsMFjE+6S9Mu1QqRwZ2tc+EUsthupE2ULO1KYZdU40njEyYzv6NeSit+oAS2JeHWPmbbQXZKf+fIwXX/EeiL3WqqWYyy9Td5gOGkcpbr+kDaeVULBTg3BOGqDrc4CMDqQ9viDymFXO/SDQMo0Vb3hkZVcYmesMI/d2lIjKikYRodTO25mcpRjsW/d8QBJhljwVlmC9oS3aV1GOUiriWn/AVI3rRKQLY1M`

**Comment by voltrue2** [comment]
Hello, 

Thank you for reporting this. It seems like a bug to me. Let me have a look into this.

Cheers!

**Comment by voltrue2** [comment]
@liuzhen2008 The each element in the array of `var purchases = iap.getPurchaseData(data);` should also contain `originalTransactionId`, would you print those out and show me also?
The receipt is a subscription, so I cannot reproduce what you have here.

Cheers!

**Comment by liuzhen2008** [comment]
@voltrue2 yes this is a subscription. I think the 6 objects in latest_receipt_info represent 1 buy and 5 renews. So i was expecting getPurchaseData to give me 6 objects. Instead it gives me 5 and 2 of them are the same object.

I printed the originalTransactionId for each purchaseData below.

```
Data transaction id
1000000381600687
1000000381600903
1000000381601336
1000000381601740
1000000381602052
1000000381602343
get purchases data transaction id
PurchaseData.transactionId: 1000000381600903
PurchaseData.originalTransactionId: 1000000381600687
PurchaseData.transactionId: 1000000381601740
PurchaseData.originalTransactionId: 1000000381600687
PurchaseData.transactionId: 1000000381600903
PurchaseData.originalTransactionId: 1000000381600687
PurchaseData.transactionId: 1000000381601740
PurchaseData.originalTransactionId: 1000000381600687
PurchaseData.transactionId: 1000000381602343
PurchaseData.originalTransactionId: 1000000381600687

```

**Comment by voltrue2** [comment]
It seems all items have the same `originalTransactionId`.
`.getPurchaseData(...)` tries to filter the duplicates(meaning items with the same originalTransactionIds), but it seems that it's failing to filter them correctly.

I hate to ask you this, but would you mind printing all properties of every item in the purchase history **WITHOUT** using `.getPurchaseData()`?

Cheers!

**Comment by liuzhen2008** [comment]
```
{ quantity: '1',
  product_id: 'basicmembership',
  transaction_id: '1000000381600687',
  original_transaction_id: '1000000381600687',
  purchase_date: '2018-03-08 19:58:55 Etc/GMT',
  purchase_date_ms: '1520539135000',
  purchase_date_pst: '2018-03-08 11:58:55 America/Los_Angeles',
  original_purchase_date: '2018-03-08 19:58:56 Etc/GMT',
  original_purchase_date_ms: '1520539136000',
  original_purchase_date_pst: '2018-03-08 11:58:56 America/Los_Angeles',
  expires_date: '2018-03-08 20:03:55 Etc/GMT',
  expires_date_ms: '1520539435000',
  expires_date_pst: '2018-03-08 12:03:55 America/Los_Angeles',
  web_order_line_item_id: '1000000038056225',
  is_trial_period: 'false',
  is_in_intro_offer_period: 'false' }
{ quantity: '1',
  product_id: 'basicmembership',
  transaction_id: '1000000381600903',
  original_transaction_id: '1000000381600687',
  purchase_date: '2018-03-08 20:03:55 Etc/GMT',
  purchase_date_ms: '1520539435000',
  purchase_date_pst: '2018-03-08 12:03:55 America/Los_Angeles',
  original_purchase_date: '2018-03-08 19:58:56 Etc/GMT',
  original_purchase_date_ms: '1520539136000',
  original_purchase_date_pst: '2018-03-08 11:58:56 America/Los_Angeles',
  expires_date: '2018-03-08 20:08:55 Etc/GMT',
  expires_date_ms: '1520539735000',
  expires_date_pst: '2018-03-08 12:08:55 America/Los_Angeles',
  web_order_line_item_id: '1000000038056226',
  is_trial_period: 'false',
  is_in_intro_offer_period: 'false' }
{ quantity: '1',
  product_id: 'basicmembership',
  transaction_id: '1000000381601336',
  original_transaction_id: '1000000381600687',
  purchase_date: '2018-03-08 20:09:15 Etc/GMT',
  purchase_date_ms: '1520539755000',
  purchase_date_pst: '2018-03-08 12:09:15 America/Los_Angeles',
  original_purchase_date: '2018-03-08 19:58:56 Etc/GMT',
  original_purchase_date_ms: '1520539136000',
  original_purchase_date_pst: '2018-03-08 11:58:56 America/Los_Angeles',
  expires_date: '2018-03-08 20:14:15 Etc/GMT',
  expires_date_ms: '1520540055000',
  expires_date_pst: '2018-03-08 12:14:15 America/Los_Angeles',
  web_order_line_item_id: '1000000038056264',
  is_trial_period: 'false',
  is_in_intro_offer_period: 'false' }
{ quantity: '1',
  product_id: 'basicmembership',
  transaction_id: '1000000381601740',
  original_transaction_id: '1000000381600687',
  purchase_date: '2018-03-08 20:14:30 Etc/GMT',
  purchase_date_ms: '1520540070000',
  purchase_date_pst: '2018-03-08 12:14:30 America/Los_Angeles',
  original_purchase_date: '2018-03-08 19:58:56 Etc/GMT',
  original_purchase_date_ms: '1520539136000',
  original_purchase_date_pst: '2018-03-08 11:58:56 America/Los_Angeles',
  expires_date: '2018-03-08 20:19:30 Etc/GMT',
  expires_date_ms: '1520540370000',
  expires_date_pst: '2018-03-08 12:19:30 America/Los_Angeles',
  web_order_line_item_id: '1000000038056312',
  is_trial_period: 'false',
  is_in_intro_offer_period: 'false' }
{ quantity: '1',
  product_id: 'basicmembership',
  transaction_id: '1000000381602052',
  original_transaction_id: '1000000381600687',
  purchase_date: '2018-03-08 20:19:30 Etc/GMT',
  purchase_date_ms: '1520540370000',
  purchase_date_pst: '2018-03-08 12:19:30 America/Los_Angeles',
  original_purchase_date: '2018-03-08 19:58:56 Etc/GMT',
  original_purchase_date_ms: '1520539136000',
  original_purchase_date_pst: '2018-03-08 11:58:56 America/Los_Angeles',
  expires_date: '2018-03-08 20:24:30 Etc/GMT',
  expires_date_ms: '1520540670000',
  expires_date_pst: '2018-03-08 12:24:30 America/Los_Angeles',
  web_order_line_item_id: '1000000038056364',
  is_trial_period: 'false',
  is_in_intro_offer_period: 'false' }
{ quantity: '1',
  product_id: 'basicmembership',
  transaction_id: '1000000381602343',
  original_transaction_id: '1000000381600687',
  purchase_date: '2018-03-08 20:24:30 Etc/GMT',
  purchase_date_ms: '1520540670000',
  purchase_date_pst: '2018-03-08 12:24:30 America/Los_Angeles',
  original_purchase_date: '2018-03-08 19:58:56 Etc/GMT',
  original_purchase_date_ms: '1520539136000',
  original_purchase_date_pst: '2018-03-08 11:58:56 America/Los_Angeles',
  expires_date: '2018-03-08 20:29:30 Etc/GMT',
  expires_date_ms: '1520540970000',
  expires_date_pst: '2018-03-08 12:29:30 America/Los_Angeles',
  web_order_line_item_id: '1000000038056406',
  is_trial_period: 'false',
  is_in_intro_offer_period: 'false' }

```

**Comment by voltrue2** [comment]
@liuzhen2008 Would you try this commit cec5c6b451c0d66224a251539dcac133fe6f99f2 ?
You should have only one item with .getPurchaseData()

**Comment by liuzhen2008** [comment]
I don't think it is quite right. I am getting empty array [] after calling .getPurchaseData() on develop branch

**Comment by voltrue2** [comment]
Hmmm.. Interesting. Let me have another look.

**Comment by liuzhen2008** [comment]
I think you can easily run my receipt you'd get the same result.

```
    iap.setup(function() {
      iap.validate(iap.APPLE, req.param("receipt"), function(error, data) {
        for (var i = 0; i < data.latest_receipt_info.length; i++) {
          console.log(data.latest_receipt_info[i]);
        }
      });
    })

```

**Comment by voltrue2** [comment]
I need to have your secret to do that because your receipt is a subscription, which is something I would not like to do for obvious reason.

**Comment by liuzhen2008** [comment]
Right.. sorry.

**Comment by voltrue2** [comment]
It's all good. I will check my change and run more tests. Thank you for sticking round for my debugging. I will have updates on this shortly.

**Comment by voltrue2** [comment]
Thank you! I appreciate the help.

**Comment by voltrue2** [comment]
@liuzhen2008 
Thank you for the wait. I spotted the issue with my previous change.
Would you please test against this: bb23b8f0c053becd8c55eace00058302afbd20f5 ?

Cheers

**Comment by liuzhen2008** [comment]
I can confirm i am no longer getting duplicated purchaseData. Only got 1 instead.

I personally am not sure why I should only get one. And if i do only get one, should I at least get the latest renew?

But yes! no duplicates!

**Comment by voltrue2** [comment]
So the idea is that now the only item you get is the latest of the duplicate, which should mean that, it is your only valid receipt because the reset are already old.

**Comment by liuzhen2008** [comment]
In my test case, the purchase data i received is 

```
[ { quantity: 1,
    productId: 'basicmembership',
    transactionId: '1000000381601740',
    originalTransactionId: '1000000381600687',
    purchaseDate: '2018-03-08 20:14:30 Etc/GMT',
    purchaseDateMs: 1520540070000,
    purchaseDatePst: '2018-03-08 12:14:30 America/Los_Angeles',
    originalPurchaseDate: '2018-03-08 19:58:56 Etc/GMT',
    originalPurchaseDateMs: 1520539136000,
    originalPurchaseDatePst: '2018-03-08 11:58:56 America/Los_Angeles',
    expiresDate: '2018-03-08 20:19:30 Etc/GMT',
    expiresDateMs: 1520540370000,
    expiresDatePst: '2018-03-08 12:19:30 America/Los_Angeles',
    webOrderLineItemId: 1000000038056312,
    isTrialPeriod: 'false',
    isInIntroOfferPeriod: 'false',
    bundleId: 'love.thecove.app',
    expirationDate: 1520540370000 } ]
```

However there is a more recent RENEW 

```
{ quantity: '1',
  product_id: 'basicmembership',
  transaction_id: '1000000381602343',
  original_transaction_id: '1000000381600687',
  purchase_date: '2018-03-08 20:24:30 Etc/GMT',
  purchase_date_ms: '1520540670000',
  purchase_date_pst: '2018-03-08 12:24:30 America/Los_Angeles',
  original_purchase_date: '2018-03-08 19:58:56 Etc/GMT',
  original_purchase_date_ms: '1520539136000',
  original_purchase_date_pst: '2018-03-08 11:58:56 America/Los_Angeles',
  expires_date: '2018-03-08 20:29:30 Etc/GMT',
  expires_date_ms: '1520540970000',
  expires_date_pst: '2018-03-08 12:29:30 America/Los_Angeles',
  web_order_line_item_id: '1000000038056406',
  is_trial_period: 'false',
  is_in_intro_offer_period: 'false' }

```

**Comment by voltrue2** [comment]
Hmmm... That is strange. my test case against the array you posted here gives me the item with the one below:

This is the expected and correct one. I will have to look into this a little more.

Thanks for double checking!

```
{ quantity: '1',
  product_id: 'basicmembership',
  transaction_id: '1000000381602343',
  original_transaction_id: '1000000381600687',
  purchase_date: '2018-03-08 20:24:30 Etc/GMT',
  purchase_date_ms: '1520540670000',
  purchase_date_pst: '2018-03-08 12:24:30 America/Los_Angeles',
  original_purchase_date: '2018-03-08 19:58:56 Etc/GMT',
  original_purchase_date_ms: '1520539136000',
  original_purchase_date_pst: '2018-03-08 11:58:56 America/Los_Angeles',
  expires_date: '2018-03-08 20:29:30 Etc/GMT',
  expires_date_ms: '1520540970000',
  expires_date_pst: '2018-03-08 12:29:30 America/Los_Angeles',
  web_order_line_item_id: '1000000038056406',
  is_trial_period: 'false',
  is_in_intro_offer_period: 'false' }
```

**Comment by voltrue2** [comment]
No response. Considered fixed.
