### ISSUE TITLE
1.8.9 failing build

### ISSUE THREAD

**Issue by a-koka** [voltrue2/in-app-purchase#160]
I'm still on `1.7.2` and would love to get the new features. The `1.8.9` build is failing though. Is there an expectation on when this will be resolved?

Thanks!

**Comment by voltrue2** [comment]
Hello,

Thank you for reaching out.
Let me have a look at it and see what the issue is.

Cheers!

**Comment by voltrue2** [comment]
I re-ran the CI and now it passed.
I am using some Apple sandbox receipts in the tests and they time out quite a lot.
It might be the cause of random failure of the tests.

Cheers

**Comment by a-koka** [comment]
Thanks for always staying on top of the issue @voltrue2. You're the best!
