### ISSUE TITLE
iap.getPurchaseData for iOS not fetching latest_receipt_info

### ISSUE THREAD

**Issue by skleest** [voltrue2/in-app-purchase#163]
Seems to be a small but critical bug - submitted PR #162

**Comment by jianpingw** [comment]
I have the same issue and I think PR #162 submitted by @skleest should fix the issue.

**Comment by voltrue2** [comment]
Hello I have an update on this issue.
Would you mind having a look it PR #162  and Commit: fd839f12791c8fe6da1686118576609f64b7cb77

Cheers!
