### ISSUE TITLE
keeps getting error on android , says Failed to validate against: undefined Error: missing public key

### ISSUE THREAD

**Issue by mobigaurav** [voltrue2/in-app-purchase#164]
Hi,

Thanks for your node module. It works very well for my iOS project's. 
But i am facing one issue with Android- 

Below is my code - 

`'use strict';

console.log('Loading function');

var iap = require('in-app-purchase');

exports.handler = (event, context, callback) => {

var androidReceiptString = {
  "orderId":"GPA.3351-2265-8541-88205",
  "packageName":"org.ieee.mobile.sa.nesc",
  "productId":"org.ieee.mobile.sa.nesc.premium",
  "purchaseTime":1488769384383,
  "purchaseState":0,
  "purchaseToken":"dnipacadlpfpkaaachgpmakk.AO-J1OzSZ1nZxr0Bt2oYfeEQ0L975nGqRtZcEoI_grlclkCpHj9_Lr7zkITAszS8ZBfxP32QCYJkSEBWVH2TWMulF7bgaJqNHholS4aJ1KRxaqEh_dy4zyRzXKXg52oJUC_oMdCcG1LQJ0Ui2zQLZ_5h8LepU3760A"
  
}
var androidSignature = 'dZ+KkgSPRyMx1We9DqC80fNiBAGiHN5aVfDunc0vqDRW26fXIFiSpkXrX4WI10WvdJsFqphfmBJUd2LgEnq/4K37Bk8MD35QNwh6/f3C7fGZtnrcxXjV2B3nf1ZJrCznHqrUg+EIHoP+fN/+UfAGz4nhUMRF/mDbbkiN6GWltcFSNntOlX5Yb30zIe1s+NXGysUdkuF4akNISuTitx+3baxKCTH2L/Zb2a2PPzlD0KTJJrXGtWPWl/IjrI+08RmeCSLD432i2qqUdhlXXt3199js2bguavM4vhA20FuQgOacMZ2L+AK41f0z+jM2TxzOEUyYbSvx1+GqbjFFI+Lczg=='

  var googleReceipt = {
      "signature": androidSignature,
      "data":JSON.stringify(androidReceiptString)
  }

 
  console.log('Google receipt is'+JSON.stringify(googleReceipt));
  
iap.config({
    verbose:true,
    googlePublicKeyStrLive: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyCiZw7R8dVHxDOlvcIFTLjHxc8DyPeklur5DHbkM6lZ20zJAbCBMYUScO6O4X0Rt6KPBL3VbtFLl0TaKuSFbeKutd5Bys8ectK4zgGrMgdKEpbeZhxdGVKMHUZmy3RWeMMCNNCaTmPXqrz3rf2Dxj3hyBub5EMd41XpyjgEdwNtnt0MPByUBKoj69g0cwANHcrwjexFcuATiP9VTr7GHS5ipsgYKX91o1Rljmbu/BFr5Nyq6P62cYGXFj5hSt3zmgBTqeh9o9Ohzy17DhUQgOsOQyQ1gxnTByeBPdjLdgJRKExvRArNMjjQNNfmUC5NJdb48wgbiQAzHOW3o6LxHSwIDAQAB'
});

  iap.validate(iap.GOOGLE,googleReceipt, function (error, response) {
    if (error) {
      // Failed to validate
      console.log('validation error android is >'+JSON.stringify(error));
    }
    if (iap.isValidated(response)) {
      // Succuessful validation
      console.log('validation Google is >'+JSON.stringify(response));
    }
  });

}

`

I get following error- 
`2018-04-03T05:52:56.745Z	41a56d83-3703-11e8-b928-31fd302a83d1	[1522734776745][VERBOSE] <Google> Validation w/ public key
2018-04-03T05:52:56.745Z	41a56d83-3703-11e8-b928-31fd302a83d1	[1522734776745][VERBOSE] <Google> Try validate against live public key: undefined
2018-04-03T05:52:56.745Z	41a56d83-3703-11e8-b928-31fd302a83d1	[1522734776745][VERBOSE] <Google> Failed to validate against: undefined Error: missing public key
    at validatePublicKey (/var/task/node_modules/in-app-purchase/lib/google.js:734:13)
    at validateMethod (/var/task/node_modules/in-app-purchase/lib/google.js:216:4)`

Please help me out.

**Comment by voltrue2** [comment]
Hello,
  

  
You don’t have to stringify data part of your receipt. The module handles it for you.
  
I will try to reproduce the issue you are having on my end also.
  

  
Lastly, Is this receipt a subscription? If it is then you need to add google api key and secret to your configuration.
  

  
Cheers!
  

  
  

  
  
>

**Comment by mobigaurav** [comment]
Hi,

I tried removing JSON stringify receipt part i still get same response. The receipt is not a subscription.
One thing which i noticed is when i run everything on online portal it gives me success response.
 
![screen1-android](https://user-images.githubusercontent.com/8948442/38257044-860c71d0-372d-11e8-819b-bc51aa8b6eb6.png)

**Comment by voltrue2** [comment]
Hello
  

  
How are you testing this? I know that signature can get corrupt if you test it with curl where “+” becomes a space.
  

  
Cheers
  

  
  

  
  
>

**Comment by mobigaurav** [comment]
I  copied signature and receipt which i get from response and tested in AWS lambda.

**Comment by voltrue2** [comment]
So I looked at the code you provided me with.
The issue that you have is because you do not call `.setup()`.
Below is what you need to do:

```javascript
iap.config(configData);
iap.setup()
.then(() => {
  iap.validate(receipt)
  .then(...)
  .catch(...);
})
.catch(...)
```

Now I also tested your receipt and the public key with the fixed code, but the validation of your receipt fails. 
This time the error is caused by the receipt not matching with the public key.

Cheers!

**Comment by mobigaurav** [comment]
When i changed the code to first do iap.setup() call, It says cant read property then of undefined. I am using version 1.6.0 of the module. let me know if i have to upgrade it to remove the error.

**Comment by mobigaurav** [comment]
I got it working using below code: 

iap.setup(function(error,response){
  
   iap.validate(iap.GOOGLE,googleReceipt, function (error, response) {
    if (error) {
      // Failed to validate
      console.log('validation error android is >'+error);
    }
    if (iap.isValidated(response)) {
      // Succuessful validation
      console.log('validation Google is >'+JSON.stringify(response));
    }
  });
  });

Thanks for all the Help!

**Comment by voltrue2** [comment]
Awesome!
