### ISSUE TITLE
Readme readability

### ISSUE THREAD

**Issue by indrek-koue** [voltrue2/in-app-purchase#165]
First i want to say thats this is very good library and really helpful and I like it.

Only one small issue: the readability on readme. Its too long for one page and a lot of repetitive info.

How it could be improved:
- separate changelog and setup instructions into separate pages
- one main example which covers most important info about setup
- separate platform specific things into different pages
  

Idea for example structure:

**Setup**
npm install In-App-Purchase

**How To Use It**

```
var inAppPurchase = require('in-app-purchase');
inAppPurchase.config({
    amazonAPIVersion: 2,
    secret: "abcdefghijklmnoporstuvwxyz", // this comes from Amazon
    applePassword: "1234567890abcdef1234567890abcdef", // this comes from iTunes Connect
    googlePublicKeyPath: "path/to/public/key/directory/" // this is the path to the directory containing iap-sanbox/iap-live files
    rokuApiKey: "1234567890abcdef1234567890abcdef", // this comes from Roku Developer Dashboard
    googleAccToken: "PLAY_STORE_API_ACCESS_TOKEN", //optional, for google play subscriptions
    clientId: '<Google Play client ID>', //optional, for google play subscriptions
    clientSecret: '<Google Play client secret>', //optional, for google play subscriptions
    refreshToken: '<Google Play refresh token>' //optional, for google play subscriptions
    test: true //For Apple and Google, the module can run in test mode so that it skipps production validation.
    verbose: true //The module can optionally turn on verbose debug log.
});

iap.setup(function (error) {
    if (error) {
        return console.error('something went wrong...');
    }
    // iap is ready
    iap.validate(receipt, function (err, res) {
        if (err) {
            return console.error(err);
        }
        if (iap.isValidated(res)) {
            // yay good!
        }
    });
});

```

This single example basically covers most of the current readme.

**Comment by voltrue2** [comment]
Hello!

Thank you for your suggestion. I will definitely try to improve README.

Cheers!

**Comment by voltrue2** [comment]
Thank you for this idea!

Check out below: 7733e314e42ce123bf756b521f919662c29c01b5

**Comment by rikur** [comment]
Looks better. However I think `refreshToken` is internal to the lib and not needed for Google Play configuration. Only `googleRefToken` is needed AFAIK.

Also, the ENV variable readme seems to be flawed:
```export=GOOGLE_IAB_PUBLICKEY=PublicKeyHerePlz```

The code is looking for `GOOGLE_IAB_PUBLICKEY_LIVE` and `GOOGLE_IAB_PUBLICKEY_SANDBOX` instead.

**Comment by rikur** [comment]
More config property names seem to be messed up..

```
clientId: '<Google Play client ID>', //optional, for google play subscriptions
clientSecret: '<Google Play client secret>', //optional, for google play subscriptions
refreshToken: '<Google Play refresh token>' //optional, for google play subscriptions
```
should be
```
googleClientID: '<Google Play client ID>', //optional, for google play subscriptions
googleClientSecret: '<Google Play client secret>', //optional, for google play subscriptions
googleRefToken: '<Google Play refresh token>' //optional, for google play subscriptions
```

**Comment by voltrue2** [comment]
Hello,

Thank you for checking the changes!

I will fix them!

Cheers!
