### ISSUE TITLE
Questions - Google Validation, Calling .setup() More Than Once

### ISSUE THREAD

**Issue by willswinson** [voltrue2/in-app-purchase#166]
Hey guys, had a few questions related to the project that I couldn't find clear answers for in the README:

1) Do you have to call **iap.setup()** before every validation call as in the example code?  Or just once after config?

2) If I do not provide API access to Google Play (with the client id, secret, access token, and refresh token), will it still validate consumable (non-subscription) purchases with Google Play?  Or does that only apply to subscriptions?  I would prefer to not include this information, and I do not have subscriptions, but I would still like to validate my non-sub IAPs through Google Play.

3) Just to make sure, if I provide **googlePublicKeyStrLive** then I do NOT have to include my key file, right?

Thanks!

**Comment by voltrue2** [comment]
Hello,   
  

  
1. You need to call iap.setup() before you do anything. Please do keep in mind the function is asynchronous ;)
  

  
2. It can validate without providing API access. Instead you need to provide the public key. With this you cannot validate subscription though.
  

  
Cheers
  

  
  

  
  
>
