### ISSUE TITLE
Incorrect isTrial value in purchaseData

### ISSUE THREAD

**Issue by a-koka** [voltrue2/in-app-purchase#167]
`getPurchaseData` is returning a value of true for `isTrial` even when `validate` returns `is_trial_period` as false. I've only tested this for Apple subscriptions and I'm guessing that there is something missing in the logic which translates the result from validate to purchaseData.

**Comment by voltrue2** [comment]
Hello,

Thank you for reporting this. I will look into it!

Cheers!
