### ISSUE TITLE
[NPM] - Install

### ISSUE THREAD

**Issue by fadao23** [voltrue2/in-app-purchase#168]
Hello,

I try to install the last version of the in-app-purchase with : 

npm i in-app-purchase

But i got this error : 

`npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'`

This problem come from my machine or npm ? 

Thanks.

-- 
Fernando BORJA

**Comment by voltrue2** [comment]
Hi there   
  

  
As the warning message suggests, you don’t have package.json file. It isn’t an error and the module should have been installed fine, but I suggest you to have package.json for your application.
  

  
Cheers   
  

  
  

  
  
>
