### ISSUE TITLE
productId is equal to subscriptionId?

### ISSUE THREAD

**Issue by egermano** [voltrue2/in-app-purchase#169]
https://github.com/voltrue2/in-app-purchase/blob/691b0d2e10d594184a087cd7f131889e7f3fd9b4/lib/google.js#L572

I didn't find any Google documentation about that. Can you explain to me where can I find this?

**Comment by voltrue2** [comment]
Hello,

This is simply a matter of variable name.
In our case here, we use the variable called `subscriptionID` to carry the value of product ID,
but for a subscription item, the value there is actually the ID of the subscription item.

Hope this clears up the confusion somewhat.

Cheers!
