### ISSUE TITLE
[iOS] Renewable subscription original_transaction_id

### ISSUE THREAD

**Issue by HelloChunWei** [voltrue2/in-app-purchase#170]
Hi,

I have some problem in Renewable subscription original_transaction_id.

In `var data = iap.getPurchaseData(response, { ignoreExpired: false })`

I expect this function will return all objects of all transactions whether the transaction is expired or not. However,  it returns only the objects of the first transaction, but doesn't return the objects of the other transactions.

For example: 
```
{
"quantity": "1",
"product_id": "1 month membership",
"transaction_id": "00000001",
"original_transaction_id": "00000001",
"purchase_date": "2018-04-01 00:00",
......
"expires_date": "2018-04-30 00:00",
.........
..........
}
```
I found out the problem in lib/apple.js
```
for (var i = 0, len = list.length; i < len; i++) {
   var item = list[i];
   var tid = item['original_' + REC_KEYS.TRANSACTION_ID];
   var exp = getSubscriptionExpireDate(item);

   if (options && options.ignoreExpired && exp && Date.now() - exp >= 0) {
	// we are told to ignore expired item and it is expired
	continue;
   }

    if (tids.indexOf(tid) != -1) {
	/* avoid duplicate and keep the latest
	there are cases where we could have 
	the same "time" so we evaludate <= instead of < alone */
	continue;
   }
........
}
```
In `if (tids.indexOf(tid) != -1)` it filters out the transactions which have the same original_transaction_id and returns only the first transaction.

But when App Store's renewable Subscriptions are in the same subscription group, they will have the same original_transaction_id.

For example:
```
{
"quantity": "1",
"product_id": "1 month membership",
"transaction_id": "00000001",
"original_transaction_id": "00000001",
"purchase_date": "2018-04-01 00:00",
"purchase_date_ms": ".......",
.........
"expires_date": "2018-04-30 00:00",
..........
},

{
"quantity": "1",
"product_id": "1 month membership",
"transaction_id": "00000002",
"original_transaction_id": "00000001",
"purchase_date": "2018-05-01 00:00",
"purchase_date_ms": ".......",
.........
"expires_date": "2018-05-31 00:00",
..........
}
```
So, `var tid = item['original_' + REC_KEYS.TRANSACTION_ID];`  that should be  `var tid = item[REC_KEYS.TRANSACTION_ID];`.

In that way, it should be able to return all transactions which have the same otiginal_transaction_id.

Please kindly advise whether my idea is correct.

**Comment by voltrue2** [comment]
Hello,

The code you are referring to actually returns the latest item of the same transaction ID.
If you look at line 225 to 231:

```javascript
/*
we sort list by purchase_date_ms to make it easier
to weed out duplicates (items with the same original_transaction_id)
purchase_date_ms DESC
*/
list.sort(function (a, b) {
  return parseInt(b[REC_KEYS.PURCHASE_DATE_MS], 10) > parseInt(a[REC_KEYS.PURCHASE_DATE_MS], 10);
});
```

As far as I am aware, only the latest item with the same transaction ID matters.
I believe the current logic makes sense in that regard.

Cheers

**Comment by voltrue2** [comment]
Hello,

Actually the sort function should have been:

```javascript
return parseInt(b[REC_KEYS.PURCHASE_DATE_MS], 10) - parseInt(a[REC_KEYS.PURCHASE_DATE_MS], 10);
```

Thank you for pointing this out. I will fix this!

Cheers!

**Comment by lincolnthree** [comment]
Hmmm... out of curiosity. What kind of downstream affects would be caused by this. Incomplete transaction data being returned from validated receipts?
