### ISSUE TITLE
How can I get base64 string from the receiptURL

### ISSUE THREAD

**Issue by immanoj16** [voltrue2/in-app-purchase#174]
Hey @voltrue2, I am doing a project using electron. And I want to add `inAppPurchase` for Mac App Store. So the `inAppPurchase` api gives the url of the receipt which is locally saved somewhere. So how can I get the base64 string from the receiptURL. Thank you for the nice project.

**Comment by voltrue2** [comment]
Hello, To get a receipt from Apple you have to connect to Apple's server first to request for a receipt (base64 encoded string).
With that said if your project stores the receipt somewhere on your local machine, you need to find where is and give it to the module, which should be running on your server.

Cheers

**Comment by voltrue2** [comment]
No response
