### ISSUE TITLE
[iOS]: Cancelled subscription being received as expired

### ISSUE THREAD

**Issue by a-koka** [voltrue2/in-app-purchase#175]
`iap.validate` is returning an error for an active but cancelled subscription. As you can see, this subscription was cancelled yesterday but it is still active for another 11 months. Below is the response from `iap.validate`. Somehow a cancelled reciept is being incorrectly reported as expired and thus `iap.getPurchaseData` doesn't return anything.

```
{
  "status": 21006,
  "message": "This receipt is valid but the subscription has expired. When this status code is returned to your server, the receipt data is also decoded and returned as part of the response.",
  "auto_renew_status": 0,
  "latest_expired_receipt_info": {
    "original_purchase_date_pst": "2018-04-27 06:49:54 America/Los_Angeles",
    "cancellation_date_ms": "1526490968000",
    "quantity": "1",
    "cancellation_reason": "0",
    "unique_vendor_identifier": "1BEF4D18-49E6-4AB7-A5FD-D6CA7A87B2AB",
    "bvrs": "1",
    "expires_date_formatted": "2019-04-27 13:49:53 Etc/GMT",
    "is_in_intro_offer_period": "false",
    "purchase_date_ms": "1524836993000",
    "expires_date_formatted_pst": "2019-04-27 06:49:53 America/Los_Angeles",
    "is_trial_period": "false",
    "item_id": "1280531126",
    "unique_identifier": "04451921342e01bcde1fd00a7ae4a6552c62c242",
    "original_transaction_id": "60000429490195",
    "expires_date": "1556372993000",
    "app_item_id": "1188877442",
    "transaction_id": "60000429490195",
    "web_order_line_item_id": "60000100858463",
    "original_purchase_date": "2018-04-27 13:49:54 Etc/GMT",
    "cancellation_date": "2018-05-16 17:16:08 Etc/GMT",
    "product_id": "com.foo.bar",
    "purchase_date": "2018-04-27 13:49:53 Etc/GMT",
    "purchase_date_pst": "2018-04-27 06:49:53 America/Los_Angeles",
    "cancellation_date_pst": "2018-05-16 10:16:08 America/Los_Angeles",
    "bid": "com.foo.bar",
    "original_purchase_date_ms": "1524836994000"
  },
  "cancellation_date": "2018-05-16 17:16:08 Etc/GMT",
  "auto_renew_product_id": "com.foo.bar",
  "receipt": {
    "original_purchase_date_pst": "2018-04-27 06:49:54 America/Los_Angeles",
    "quantity": "1",
    "unique_vendor_identifier": "1BEF4D18-49E6-4AB7-A5FD-D6CA7A87B2AB",
    "bvrs": "1",
    "expires_date_formatted": "2019-04-27 13:49:53 Etc/GMT",
    "is_in_intro_offer_period": "false",
    "purchase_date_ms": "1524836993460",
    "expires_date_formatted_pst": "2019-04-27 06:49:53 America/Los_Angeles",
    "is_trial_period": "false",
    "item_id": "1280531126",
    "unique_identifier": "04451921342e01bcde1fd00a7ae4a6552c62c242",
    "original_transaction_id": "60000429490195",
    "expires_date": "1556372993460",
    "app_item_id": "1188877442",
    "transaction_id": "60000429490195",
    "web_order_line_item_id": "60000100858463",
    "version_external_identifier": "826524987",
    "product_id": "com.foo.bar",
    "purchase_date": "2018-04-27 13:49:53 Etc/GMT",
    "original_purchase_date": "2018-04-27 13:49:54 Etc/GMT",
    "purchase_date_pst": "2018-04-27 06:49:53 America/Los_Angeles",
    "bid": "com.foo.bar",
    "original_purchase_date_ms": "1524836994819"
  },
  "cancellation_reason": "0"
}
```

**Comment by voltrue2** [comment]
Hello,

Thank you for the report. I will have a look!

Cheers

**Comment by voltrue2** [comment]
The module looks at `cancelation_date` in the response from Apple and if the value of `cancelation_date` is there, the module considers the item to be either canceled or expired.

**Comment by voltrue2** [comment]
This should fix the issue.
Please let me know if you still have the same problem.

Cheers

**Comment by a-koka** [comment]
Thanks for the quick turnaround as always @voltrue2. Your commitment to keeping this project up-to-date is commendable. Unfortunately, the fix doesn't work. I did a bit of debugging and here's what I've discovered.

We are receiving a status code of `21006` for subscriptions that are cancelled. Both active and inactive subscriptions are returning the same status code. Thus we need to update the `errorMap` and also need some separate logic to determine if a cancelled subscription is still active or not.

I changed the following line in `validatePurchase` and now I see a `failed to validate purchase` error. Looks like this is a bit more involved and perhaps you'll have a better handle on how to solve this.

```
      // apple responded with error
      if (data.status > 0 && data.status !== 21007 && data.status !== 21002 && data.status !== 21006) {
```

**Comment by a-koka** [comment]
Looks like the `errorMap` is pulled out of [here](https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html) which makes me really confused as my research suggests that `21006` is coming back for an active purchase as well as you can see in my original post . I'm happy to jump on a screen-share call with you if you don't have productions receipts to verify some of these situations.

Thanks again!

**Comment by voltrue2** [comment]
Hello,

Thank you for following up on this issue. I made another commit: c70bf2813d6a1c9fbfe6d75e223852ef75cec257

Would you mind having to look at it?

Cheers!

**Comment by a-koka** [comment]
I tested with a few different subscriptions and this is working as expected. Would you be able to push this fix live on npm sometime soon?

Thanks again!

**Comment by voltrue2** [comment]
Hello
  

  
Thanks for testing the fix. I’ll be publishing the new version very soon.
  

  
Cheers
  

  
  

  
  
>

**Comment by voltrue2** [comment]
version 1.9.7 published!

Cheers!

**Comment by marciobueno1** [comment]
Hi, I was looking for this issue, and I found that on [Apple Guide](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html)

> To check whether a purchase has been canceled by Apple Customer Support, look for the Cancellation Date field in the receipt. If the field contains a date, regardless of the subscription’s expiration date, the purchase has been canceled. With respect to providing content or service, treat a canceled transaction the same as if no purchase had ever been made.

So, with this change in the code, should I need to test afterwards with [isExpired function](https://github.com/voltrue2/in-app-purchase/blob/develop/index.js#L210)? Because this function still works correctly returning true when a subscription has been cancelled...

**Comment by a-koka** [comment]
@marciobueno1 I think we are mixing a few terminologies. Let me clarify based on my knowledge.

1. Subscriptions have an auto-renewal which can be cancelled by the user but still leaving the user with an active purchase until a certain date. This is the case for this ticket.
2. A cancellation through Apple - A user can get in touch with Apple and request a refund on a subscription or non-recurring purchase. This is the cancellation that you are referring to above if I understand correctly. If so, your understanding is correct and you should use cancellationDate. Having said that, this is a rare case with most products.
3. isExpired - This is specific to subscriptions only and usually happens after a user has cancelled a subscription and when the then current subscription period is over.

Does that help?

**Comment by marciobueno1** [comment]
@a-koka From what I understand from [Apple Site](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html)

1. In the case the user cancels the auto-renewal, the auto_renew_status field will have the value 0. No cancellation_date will appear on the receipt.
2. cancellation_date will only appear on the receipt if the user asks for a refund through Apple OR upgraded to another auto-renew subscription (that is on the same group)

So, if Apple says that if there is a cancellation_date on the receipt we should "Treat a canceled receipt the same as if no purchase had ever been made", why should we care about the expiration_date?

I don't understand why you consider a canceled subscription as ACTIVE!

**Comment by a-koka** [comment]
Looking into my original post, I can see why this confusion is arising. The JSON has a cancellation_date_ms. After getting clarification from my customer, this purchase wasn't cancelled according to her. Also the status of 21006 suggests otherwise which is why I created this in the first place.

I am investigating this further. Would be nice if you had a few production receipts that were actually cancelled to get more data. Will update this ticket with more info soon.

**Comment by marciobueno1** [comment]
Thanks, @a-koka. Unfortunately, I don't have canceled production receipts. I would ask Apple Support for this specific receipt to confirm that this subscription was not withdrawn.

**Comment by a-koka** [comment]
@voltrue2 Your input may be valuable here.

I further investigated this and although my user suggests that she didn't cancel the subscription, iTunes Connect does report a refund for that particular month and I'm now certain that the subscriptions was actually cancelled/refunded. Sorry about the original confusion @marciobueno1.

I think this brings up some valid concerns. Should `isExpired` keep the new changes and ignore cancelled/refunded receipts? I can see this being debated either way. I like it when code is more verbose and my proposal would be to introduce a `isCancelled` method.

Although I'm not using the `ignoreCanceled` flag, this would be another way to differentiate between cancelled and expired receipts. Ideally Apple doesn't send back the 21006 status for cancelled receipts but we can't control that. Let's also keep in mind that cancellations/refunds are a rare case when compared to expired subscriptions.

Until a decision is made, @marciobueno1 you can use the `cancellationDate` to determine whether a receipt is actually cancelled. I personally prefer knowing when a user cancels (refunded) vs a receipt expires.

**Comment by voltrue2** [comment]
@a-koka @marciobueno1 

Thank you both for your inputs. I do agree that if a subscription has indeed been cancelled and a refund has been made to the user, the subscription should be voided meaning that it should be considered invalid.
I am currently leaning towards adding `isCancelled`, but I am also concerned that introducing another method to determine the state of a subscription may further confuse the developers.
In any case, I do believe that we need a clean way to determine if a subscription has been cancelled or not.

**Comment by a-koka** [comment]
You're most welcome @voltrue2! You're my favorite author on GitHub, always committed to responding, very humble and kind. Keep up the good work brother!

I don't there is a right answer here as one can argue a cancelled receipt is still not expired. The vice-versa is just as valid an argument. Adding `isCancelled` also does impose implementation concerns on other platforms.

Do whatever is easiest for you. I think the documentation is more important than anything else explaining whatever you decide to do in detail to users using `isExpired` and `isCancelled`.

Cheers!

**Comment by voltrue2** [comment]
@a-koka Thanks a lot! I think I will add `isCancelled` method and make sure the documentation is accurate.

Cheers!

**Comment by jcurlier** [comment]
We have the following comment in the code:

```
/* if a subscription has been canceled,
we need to check if the receipt has expired or not...
```

It doesn't seem to match the Apple documentation:

```
To check whether a purchase has been canceled by Apple Customer Support, look for the Cancellation Date field in the receipt. If the field contains a date, regardless of the subscription’s expiration date, the purchase has been canceled. With respect to providing content or service, treat a canceled transaction the same as if no purchase had ever been made.
```

The behavior is different between Apple and Google. This is creating an issue with several customer subscriptions. Shouldn't we ignore all canceled subscription when the flag is set regardless of the expiration?

**Comment by voltrue2** [comment]
Hello,
There might have been a reason for this. Let me have a look.

Cheers
