### ISSUE TITLE
Retrieving the newly-refreshed access token (Google)

### ISSUE THREAD

**Issue by guyjoules** [voltrue2/in-app-purchase#177]
I'd like to be able to store the newly-refreshed access token so I can reuse it if needed.
For that, we need a new exported function in google.ts -
module.exports.returnToken = function (cb) { return googleTokenMap.accessToken }

As well as at the end of - module.exports.validate = function .... {
...
	return google.returnToken();
}

**Comment by voltrue2** [comment]
There is an API for this already:

`iap.refreshGoogleToken(callback [Function])`

With this, you do not need to store the token yourself instead, you can call this function whenever you need to refresh the token.

This might be missing in the documentation.

Cheers

**Comment by guyjoules** [comment]
Thanks, got it.
So, in order to call validate multiple times (once for each subscription purchase), I should call 
`iap.refreshGoogleToken(callback [Function])` first, get the access token and then feed it back to 
`iap.config` for subsequent calls?

What I'm basically looking for is a way to call validate multiple times (once for each subscription purchase) and to be able to use the same access token.

**Comment by voltrue2** [comment]
Hello, 
The module does this internally for you, so unless you're doing something outside of this module, you should not have to do this yourself.

Cheers
