### ISSUE TITLE
Update request dependency to fix nsp/vulnerability checks

### ISSUE THREAD

**Issue by MorpheusXAUT** [voltrue2/in-app-purchase#178]
As of last Wednesday (2018-05-16), a vulnerability report for the `stringstream` packages has been published: https://nodesecurity.io/advisories/664
Although the vulnerable package is not used directly by `in-app-purchase` or the importing dependency `request`, vulnerability scanners such as [nsp](https://github.com/nodesecurity/nsp) report issues with `in-app-purchase`'s dependencies, thus also failing CI builds + tests.
Version 2.86.0 of `request` seems to have removed the dependency since it was unused anyways.

Although the vulnerability report should not affect `in-app-purchase` directly, an update of the dependency would be appreciated in order to fix CI builds.

Happy to provide a PR as well, although the change should probably be minimal anyways.

**Comment by voltrue2** [comment]
Hello
  

  
Thank you for the reminder. I was actually waiting for this as I was very uncomfortable to leave this module vulnerable because of stringstream.
  
I’ll be updating the module shortly.
  

  
Cheers
  

  
  

  
  
>

**Comment by MorpheusXAUT** [comment]
Thanks for the quick response, appreciated!

**Comment by voltrue2** [comment]
Hello,

I have published `1.9.7` which contains this update.

Cheers!
