### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by baranpirincal** [voltrue2/in-app-purchase#179]
Hey, I can contribute on your project with making a logo design. What do you think about that? If you need it we can talk about design decisions as soon as possible. I am waiting your feedback, have a nice day!

Best Regards
Baran Pirinçal

**Comment by voltrue2** [comment]
Hello,
  

  
That would be really awesome!   
  

  
I would love that.
  

  
Cheers!
  

  
  

  
  
>

**Comment by voltrue2** [comment]
Awesome. I will be looking forward to it.

Cheers

**Comment by baranpirincal** [comment]
Hey @voltrue2 ,

Sorry for delay, I was too busy last week. I made my first experiment. We can change colors, add or remove something on design. Please feel free to give advice! I am waiting your feedback 👍 

![untitled-2](https://user-images.githubusercontent.com/37786733/40884290-73308e9a-6719-11e8-906c-6969b05f0fdf.jpg)

**Comment by voltrue2** [comment]
Thank you for the icons!

I think I prefer the one on the top right.

Cheers!

**Comment by baranpirincal** [comment]
@voltrue2 

Hey, I created pull-request and uploaded high-resolution .PNG and editable .SVG files!

Good luck with that!

**Comment by baranpirincal** [comment]
![inapp-firstpage](https://user-images.githubusercontent.com/37786733/41187838-a6d9864c-6bbb-11e8-86e8-07f0e7c8a7e0.jpg)

**Comment by voltrue2** [comment]
This one looks nicer!
  

  
  

  
  
>

**Comment by baranpirincal** [comment]
@voltrue2 Thanks! I made last arrangements on pull-request. Could you please check it?

**Comment by voltrue2** [comment]
Merged! Cheers
