### ISSUE TITLE
Does this module work with Mac App Store in-app purchases?

### ISSUE THREAD

**Issue by mz2** [voltrue2/in-app-purchase#18]
The wording in the README is a bit confusing on whether the module supports validating also Mac App Store receipts for in-app store purchases. Are Mac App Store in-app store receipts supported?

**Comment by voltrue2** [comment]
Hi

It should be support Mac app purchase for OSX as well.
Reference here: https://developer.apple.com/in-app-purchase/In-App-Purchase-Guidelines.pdf

Although I made this module mainly for iOS.
Please do let me know if you run into issues with OSX

**Comment by holgersindbaek** [comment]
Did you guys try it out? Is it possible to do MAS in-app purchases with this library?

**Comment by voltrue2** [comment]
Hello

The library is primarily designed to validate iOS in-app purchase receipt on a server. I do think that Mac App Store purchase works more or less the same way, but I have not intended to use it for that purpose.
I hope this answers your question.

Cheers

**Comment by holgersindbaek** [comment]
If it is only used to validate receipts, how do people do the actual in app purchase? So they use another library? 

If you don’t have any Mac examples, an iOS example would probably do. 

-- 

All the best

*Holger Sindbaek* · UI/UX Designer & Web/iOS Programmer · * * HolgerSindbaek.com ( http://holgersindbaek.com/ )

**Comment by voltrue2** [comment]
Hello

Making in-app purchase on the client-side is pretty straight forward. 
There are methods for each platform. iOS, Android, Amazon(Android), Windows and Roku respectively.
Since you mentioned that you’re building a Mac app, you don’t have to worry about cross platform stuff such as Unity and Xamarin etc.

Cheers

**Comment by holgersindbaek** [comment]
Do you have a reference to an iOS example? Or an Electron Windows example?

-- 

All the best

*Holger Sindbaek* · UI/UX Designer & Web/iOS Programmer · * * HolgerSindbaek.com ( http://holgersindbaek.com/ )

**Comment by voltrue2** [comment]
I don’t have an example at hand but you should be able find plenty on google.

Cheers
