### ISSUE TITLE
then().

### ISSUE THREAD

**Issue by hermosillo8** [voltrue2/in-app-purchase#187]
iap.setup()
        .then( () => {
            iap.validate(receipt).then(onSuccess).catch(onError);
        }).catch((error) => {
            console.log("setup error: " + error)
        });

    function onSuccess(validatedData) {
        var options = {
            ignoreExpired: true // purchaseData will NOT contain exipired subscription items
        };
        var purchaseData = iap.getPurchaseData(validateData, options);
        res.send(validatedData)
        res.end()
    }

    function onError(error) {
        console.log("validation error: " + error)
    }

The process above follows the flow in the READ ME section. When I try to run this I get an error of the then(). needs to return a value or throw. I assumed the .catch was the throw and onSuccess() I return a value. Is there something I am missing that I need to add? Sorry I have never used then().

**Comment by voltrue2** [comment]
Hello,

Would you please show me the error you get?

Cheers!

**Comment by hermosillo8** [comment]
error: Each then() should return a value or throw      promise/always-return

**Comment by voltrue2** [comment]
Hello,

Here is the working code in the unit test of this module:

```javascript
        iap.config({
            verbose: true
        });
        var receipt = fs.readFileSync(path, 'utf8');
        iap.setup()
            .then(function () {
                iap.validate(receipt).then(onSuccess).catch(onError);
            }).catch(function (error) {
                throw error;
            });

        function onSuccess(response) {
            var data = iap.getPurchaseData(response, { ignoreExpired: true });
            for (var i = 0, len = data.length; i < len; i++) {
                console.log('parsedPurchaseData:', i, data);
                assert(data[i].productId);
                assert(data[i].purchaseDate);
                assert(data[i].quantity);
            }
            done();
        }

        function onError(error) {
            throw error;
        }
```

I am not sure how you are getting this error. Would you please give me the code?

Cheers

**Comment by voltrue2** [comment]
No response... Closing

**Comment by hermosillo8** [comment]
Testing to see if this reopens this.
