### ISSUE TITLE
Config googlePublicKey in string format instead of files

### ISSUE THREAD

**Issue by matthewga0** [voltrue2/in-app-purchase#2]
Can you implement a new way to **readConfig** from stream/string instead of files, I think this way is more convenient in specific scenarios.

**Comment by voltrue2** [comment]
Hi Mathew,

The module supports reading from files and reading from env variables currently.
Let me think about this a little. 
In the meantime, could give me an example of a possible use case?

**Comment by matthewga0** [comment]
As an IAP platform, it allows developers who has no servers to store their public key in the database, it could be useful to read the key as string or stream directly from the database, maybe reduce the disk io:)

**Comment by voltrue2** [comment]
OK, so the idea is to read the public key from database and use it?

.config() function is intended to be used once when you set up the service process, so disk i/o shouldn't be much of a problem here, I think. 

With all that said, I suppose, giving an option to read public key as string wouldn't hurt... 
I hope no one will hard-code the key in their source code, though...

**Comment by voltrue2** [comment]
I pushed my first attempt to support string public key in my develop branch.
Would like to have a look?

**Comment by voltrue2** [comment]
Implemented: https://github.com/voltrue2/in-app-purchase/commit/238cdea0d0c6773597ebf297c9ce36c6bf1983f6
