### ISSUE TITLE
Google service account

### ISSUE THREAD

**Issue by maxs15** [voltrue2/in-app-purchase#202]
Is it currently possible to use a service account instead of OAuth for Google?

I think it would be great since we could create a service account for the iap module with only the necessary permissions instead of the full permissions provided by the current authentication system using OAuth.

Thanks

**Comment by maxs15** [comment]
Looks like it could be pretty easy to implement by looking at https://github.com/Wizcorp/node-iap.
The authentication system to get the accessToken is implemented in https://github.com/Wizcorp/node-iap/blob/master/lib/google/jwt.js.

What do you think about implementing it @voltrue2 ?

**Comment by voltrue2** [comment]
That is a good point. We do not need the full permission to validate receipts. I’ll look into this.
  
Thank you for the suggestion.
  

  
Cheerd
  

  
  

  
  
>

**Comment by voltrue2** [comment]
Hello,

I has taken me a while to finally get to this, but it is here now!

Commit: 709ca127bb58087d14196a890cb06155956bdb52

If you don't mind having a quick look at it, it would be great!

Cheers

**Comment by maxs15** [comment]
That's awesome @voltrue2 !!!
The code looks good, I'll try to test it this week and will let you know if I find any issue.

Thank you again 🙏
