### ISSUE TITLE
Google validation using the signed receipt string

### ISSUE THREAD

**Issue by rohanrichards** [voltrue2/in-app-purchase#204]
I am using a front-end module that is having trouble returning the transaction receipt as an object, however it is happy to return the receipt as a signed string and the signature.
Is there a way to validate Google purchases with these two items? I'm hoping to just find a workaround until I can hear back from the dev on that project to solve exactly WHY it refuses to return the receipt (before signing)

Example
```
  transactionReceipt: 'ipdajdghnchlihdcfgijiald.AO-J1Oy_ppAYRBYWPxk5rRdZ2ohXAaO4w-v4hIZOye2aYDBXI_wtDiurocZyvst3lTkgT2PbUiGP5Wmkh_egyTmndsTNqCwALp7pbOGEyTHM5E-7xLlsfLh6tUF5_S4vAhOAXrSCtQuH3uaJTBhUO82xGIC8tCTFmcNpDQz8szCYwHk2rgu9eSKRW2OjXygbarIokicnlB63y8c3G2ZIA-OeLGZmFURsAA',
  dataSignature: 'YbwVZ40AFSJsucijhmwX7Ghcnw5b2RxArozSkl42KvbuZBk+8Wo1P89Ld4ZtEWV+u1UGydAaxsUGB8ag8q1jX3IULS+J3Oz0X4FL6iBwePtIjVSMcWx+Su+tDcVX1Mk7dR1OMRBEe6UJLuQUy7Lg8QlI1XVjOgZLLtj88cGcPaJh3nq3GB1Kq08V5nYvX+14KcqDn5FbtyMdGhL+iUwNTzuzFp40lD83oUhSc1lJDRDufEobOq9+KKTRZxZx+4ijQfnUuRvmHHcGvmOgLnPjAOZDwfHhCbpseppgyvzROO9CtEyv7OoXaWdqwM4myEqFE0Zcuq/3wDdxGbySTLoHUQ==',

Is there a way I can decode the receipt string to get the original json object out of it?

**Comment by voltrue2** [comment]
Hello
  

  
I don’t think we can validate the receipt data as a bade64 string. What happens if you convert it to a buffer and JSON.parse it?
  

  
  

  
  
>

**Comment by rohanrichards** [comment]
@voltrue2 I'm not at work currently, but I may have found a way to pull the actual receipt object as a JS-Object on the front-end.

Do you have an example of how to do what you suggest? Not familiar with Buffer's.

As an aside, I will have to have a look at the source, but what is the process for validation? I assumed it would use the signature to sign the object at some stage to compare to ... something. Would it be difficult to skip this step, allowing the module to accept an *already signed* object as a string?

**Comment by voltrue2** [comment]
No response for a while. Closing
