### ISSUE TITLE
incorrect spelling of "receipt" in amazon.js

### ISSUE THREAD

**Issue by psaini14** [voltrue2/in-app-purchase#21]
Please have a look at line 81 of amazon.js.  The validatePurchase function receives the parameter "receipt", but references it as "reciept" on line 81.  This was mistaken caught while doing a global find on our own code for the same spelling mistake made by us elsewhere (we did the same thing!).  Lucky catch.

**Comment by voltrue2** [comment]
Great! Thank you for catching this. I will fix this now and also will merge publish the fix to apple.js once all unit tests are cleared.

Thanks again

**Comment by voltrue2** [comment]
Thanks again.

The typo issue has been fixed: https://github.com/voltrue2/in-app-purchase/commit/8ecca6be06a4f0959cd9741e5e70342b46812d63
