### ISSUE TITLE
Typo in windows getPurchaseData

### ISSUE THREAD

**Issue by IchordeDionysos** [voltrue2/in-app-purchase#210]
Isn't there a typo in here?
https://github.com/voltrue2/in-app-purchase/blob/875ae40d91fa333bbf6ca286cd7529c2d2251288/lib/windows.js#L113

**Comment by voltrue2** [comment]
Hello
  

  
You’re right! Thank you for pointing it out. I will fix that!
  

  
Cheers
  

  
  

  
  
>

**Comment by voltrue2** [comment]
Done. Thank you for reporting it.
