### ISSUE TITLE
Support empty receipts

### ISSUE THREAD

**Issue by IsaiahJTurner** [voltrue2/in-app-purchase#216]
I'd like to access the receipt data for empty receipts but https://github.com/voltrue2/in-app-purchase/blob/f014d852ba9d65bea65fa4b24a53e291ffc24049/lib/apple.js#L362-L388 prevents that. Any way a flag could be added to disable this behavior?

**Comment by voltrue2** [comment]
Hello,

Thanks for reaching out. What if I pass the decoded receipt data to Promise's reject function along with the error instead? 
If you use the callback, it behaves that way already.

**Comment by voltrue2** [comment]
I made the change and pushed it to develop branch. Here is the commit: 14e43a6caae98c52e4272d75d373a387286b8653

If this works out for you, I could make a proper release with the change.

Cheers!

**Comment by IsaiahJTurner** [comment]
Thank you! Going to try this out and report back. Should work fine.

**Comment by voltrue2** [comment]
Resolved!
