### ISSUE TITLE
Google insufficient permissions w/ service account

### ISSUE THREAD

**Issue by cmendes0101** [voltrue2/in-app-purchase#218]
I'm setting up service account to use with realtime developer notifications.

I set the service account to have View Financial Data permission but when i perform validate() is failed with:
Status 401 - "The current user has insufficient permissions to perform the requested operation."

Is there additional permission that is required for this setup? I tried giving Administrator permission just to see and still nothing. If I place an incorrect product id, it does error saying that product id is not correct so at least it has some permission to check.

**Comment by voltrue2** [comment]
Hello

This link may help you if you’re still getting 401 error:
https://support.google.com/googleplay/android-developer/answer/6230247?hl=en&visit_id=636729188020068309-4129873868&rd=1

Also, please make sure you’re using the latest version of this package as the previous version had a bug related to the permission.

Cheers

**Comment by cmendes0101** [comment]
Yes, I'm currently on 1.10.4 which shows latest on NPM. I'll run through that link and permission settings again.
