### ISSUE TITLE
autoRenewing

### ISSUE THREAD

**Issue by binarytracer** [voltrue2/in-app-purchase#22]
hi @voltrue2, thank you for creating this module this really help us ( with my team ) to work stuff related to apple and google in server to server approach. I just notice something on the following areas

var iap = require('in-app-purchase');
iap.config({
    'googlePublicKeyStrSandBox': "public-key-here",
    'googlePublicKeyStrLive': "public-key-here"
})
1. When setting config : 
    a. setting both the sandbox and live keys must always be the case? or it can be sandbox only or live key only?

2. Im not really sure if the this due to this module or the google itself.
Here is the siatuation :
    In our payment merchant center ( where all the orders are listed ), the order is cancelled already by the user ( android user that bought the service ) and i can confirmed also that the order is cancelled on the PAYMENT MERCHANT CENTER but when getting the response from iap.validate i got this object {
orderId: 'GPA.xxxx-xxxx-xxxx-xxxxx',
  packageName: 'xxx.xxxxxxxxxx.xxxx',
  productId: 'xxxxx',
  purchaseTime: 1445238298902,
  purchaseState: 0,
  purchaseToken: 'longest-string-here',
  autoRenewing: true,
  status: 0,
  service: 'google'
}
this is subscription type of product billing period of 1 month.

based on google docs: http://developer.android.com/google/play/billing/billing_reference.html#purchase-data-table ( table 4 reference )

autoRenewing should be false, 
purchaseState: 1, 

Am i right?

**Comment by voltrue2** [comment]
Hi @binarytracer,

Thank you for reaching out.

For the public key, sandbox is there as an optional testing for your convenience. 
You can set the same value as live for sandbox.

For the second question on autoRenewing, I believe what you described here is correct that if your purchase has been canceled, purchaseState should be 1 and autoRenewing false assuming that this purchase was not a subscription with auto-renewing.

The module is simply validating the receipt to validate its authenticity. It does not connect to google server from this module at all, so you might want to look at how you are getting this receipt from google server on your client-side.

**Comment by binarytracer** [comment]
thanks @voltrue2 for the clarification, Ive tried another module also like google-play-purchase-validator but still i got the same value.
