### ISSUE TITLE
Apple: testing expired subscription in sandbox-mode

### ISSUE THREAD

**Issue by znegva** [voltrue2/in-app-purchase#221]
Hi.

While testing auto-renewing-subscription-validation for Apple I stumbled about iTunes returning with status 21006 for expired subscriptions.
Everything I do is done with sandbox accounts and in sandbox-mode.

My code is something like this:
```
iap.config(configObject);
iap.setup().then(()=>{

  iap.validate(receipt)
  .then((validatedData)=>{
    console.log("yeah");
    console.log(validatedData);
  })
  .catch((error) => {
    console.log("oh noes");
    console.log(error);
  });

});
```

While testing my subscription everything was fine as long as the subscription was NOT expired.  
But as soon as it is expired I end up in the catch block...

After digging in the code I ended up finding out that [`tryProd`](https://github.com/voltrue2/in-app-purchase/blob/14e43a6caae98c52e4272d75d373a387286b8653/lib/apple.js#L123) does handle this special behaviour of iTunes, but [`trySandbox`](https://github.com/voltrue2/in-app-purchase/blob/14e43a6caae98c52e4272d75d373a387286b8653/lib/apple.js#L188) does not.

Is there a reason for this different behavior for production and for sandbox?
And if there is no way around this, please let me know how to test expired subscriptions with sandbox users.

Thanks a lot!

**Comment by voltrue2** [comment]
Hello,

I have updated develop branch. Would you mind testing it and see if your issue is now resolved?

Cheers!

**Comment by znegva** [comment]
Hi, thanks for your quick answer.

Your fix is working fine!
Expired-sandbox-subscriptions can now be handled inside of the regular `iap.validate(..).then` 👍 

---

As this issue is about expired subscriptions I would like to ask another question here:

I check if my subscription is expired in the following way:

```js
iap.validate(receipt)
.then((validatedData)=>{
  var purchaseData = iap.getPurchaseData(validatedData); //Array!!

  var isExpired = false;
  purchaseData.forEach((purchase)=>{
    //REVIEW: not sure if we really should check and combine ALL array entries?
    isExpired = isExpired || iap.isExpired(purchase);
  });

  if(isExpired){
    console.log("expired!");
  }else{
    console.log("valid and NOT expired");
  }
}
```

I am not sure what exactly are the entries of the `purchaseData`-Array if there are multiple.
In my tests there always was just one entry, but who knows what happens in the real world 😄

**Comment by voltrue2** [comment]
Hello
  

  
Thank you for following up! I’m glad it’s now working for you. I will publish a new version with this fix.
  

  
Regarding your question of multiple validated data, there are cases where you may have multiple purchased data but this is only true for iOS.
  
It would be better to check and remember each expiration instead of combining them as they would be separate purchased items.
  

  
Cheers
  

  
  

  
  
>

**Comment by znegva** [comment]
ok, thanks.

I am building a validation server and i know which product/subscription the current request is about (`req.body.id`), for now only combining purchasedData of this product to get my expired-state for this very product.

```js
      var isExpired = false;
      purchaseData.forEach((purchase)=>{
        //only check/combine purchases/answers of the product this request is related to!
        if(purchase.productId == req.body.id){
          isExpired = isExpired || iap.isExpired(purchase);
        }
      });
```
