### ISSUE TITLE
Failed to validate purchase - android

### ISSUE THREAD

**Issue by Yusk1450** [voltrue2/in-app-purchase#225]
Hi.
My receipt data and public key sent the Online Demo page.
getting following result. Is something wrong?

{
 "error": "failed to validate purchase",
 "response": {
   "status": 1,
   "message": "failed to validate purchase"
 }
}

Below is receipt:

{"data":{"orderId":"GPA.3353-0409-3995-57424","packageName":"jp.co.nlcc.AeruParty.Android","productId":"jp.co.nlcc.aerupartyandroid.tickets.1","purchaseState":0,"purchaseTime":1541154154796,"purchaseToken":"picfejiochkijncflcmiiiab.AO-J1OwMnYjQXi8OK87Wlg-6hYDkwAmHhmOmdZQc9L-vRUdgo9eODOGCPaUERWTLFjpzTci2-AmnNqW8LXuVE8gn7ayH8kwz-DIbhM7_EoBJ1IY_jVHUnaCKuMdmAX5aM-Xd5KGvNvbZEF5uvHseZdEQdOKUeJF2K-GafBst5oaO54qZMfnJ3bE"},"signature":"FsKbO46s4bcSyfhQTgb36UuA28j7CAb1id8qIWDVDOmpWtBsr5f0wkD16go/h1vglXGcNZ2xuT7Ico7qA5TgP+S4JWSFatJu5Z5WaTvHzkkn+ys0f2lH8FDjv0r171kSPEndQhb+LJluAVztuEJ9zKkDoQYd4FVfrn0/V5EagUOh2+zHqg1zVRtEFHbRlgmGlRDrS+knfnpKAGD5gSvfjNu0/h6KcCWkwkH+OZpt1uUfO2g/59YoMMeABFMz/93sfv915hVgcLwZTRhffkw+f6a1BAnWkztMbitFrW7b5JqRnzSeiXth9tk8fAUZ6I0cTdWPywuobFvsns/xfi6+Lw=="}

Below is public key: 

MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAomoOh35UGeq+vCwSfdUKnuE41I64iGajjUCYTTIrsPqgfwcRlVIJY5YbPyvpU9iICOOovW5XRdR5LaHaxiFyERZvMB1JyZdc8vYwzIubcgpcivrhVsAyr3boo1fD+ddxCXp6ZNw08M/CtmDgiEIHNzqFoWNXm/KIgpO66bWa+qE+KfKrirCAY3TQGn2yl2/gtVCBeH9fT6v62dh3qdyuUTbxDd+Vzp0U9OLB1wUHipbfg0KMUIHVCi+SfsFTrydah9L1lBiXpXEGGYFDgTieOVz2GLm0kxxgNYNLMpgiVZcAemjAst40WbdAOPrsbWQihCsOF+is0WroFxtuKQmTeQIDAQAB

**Comment by voltrue2** [comment]
Hello

It means either the receipt data or the public key are incorrect.
The format of the receipt is fine though.

Cheers
