### ISSUE TITLE
Error: Missing Package Name

### ISSUE THREAD

**Issue by edu4024** [voltrue2/in-app-purchase#229]
Hi.
My receipt data looks like 
 { receipt:
   { signature: 'bLXiLRd9su/upLeQiziY5huQ8ii/Ij83p9Wg/VZqSnLfV+3KHWaA4dKt2RoshfeTnLqU4EBtTVhqE6wZP4iywuIiI+qKvS45miU0lib6BbWgTbAqQlD4YnPIKIrZVEQa4DD/L7NKwytORnTwSOpF07UJJ5W+DW343bTtIMASkoeYerKJq/R+YVvfqFiT/DT6ICa9m0R4Bu6L6F56ex4CIs+r9yb50pFWw1/8LWjFNOdltDthZ2xkjODsr5ReEzNgbLTNdSbYXCqrP/yp2qFfTxe193XGkIkGl3fVPuTGPc2l21owNWT08FA5gMRk5Shhsm6EgbQc2HySSCdgj3M4RQ==',
     productId: 'idcmdescription_0',
     transactionId: 'adfbgffhabohcbhnhcfiljfk.AO-J1OytgvvIYFA3Iclt5XOLzWOEEdLk4A9Xx66qWUjHzRnAJXicCclvuIZ6TSLH-0I0Ibl8P4TbnaHN8T3o5HZfOrg4qU_oDqEVePPcqvB429GCh1sOpjiYIih7UCYcVV7Im36IcF3H',
     type: 'subs',
     productType: 'subs',
     receipt: '{"orderId":"GPA.3326-1192-0251-53155","packageName":"io.concertmasterapp","productId":"idcmdescription_0","purchaseTime":1542898283931,"purchaseState":0,"purchaseToken":"adfbgffhabohcbhnhcfiljfk.AO-J1OytgvvIYFA3Iclt5XOLzWOEEdLk4A9Xx66qWUjHzRnAJXicCclvuIZ6TSLH-0I0Ibl8P4TbnaHN8T3o5HZfOrg4qU_oDqEVePPcqvB429GCh1sOpjiYIih7UCYcVV7Im36IcF3H","autoRenewing":true}' } }
my iap.config({
    googlePublicKeyPath: '../../../config/api-8798397623611679840-192847-42d1a4a4da1a',
    googlePublicKeyStrLive: androidPass.googlePublicKey,
    googleAccToken: androidPass.googleAccToken,
    googleRefToken: androidPass.googleRefToken,
    googleClientID: androidPass.googleClientID,
    googleClientSecret: androidPass.googleClientSecret,
    googleServiceAccount: {
        clientEmail: androidPass.clientEmail,
        privateKey: androidPass.privateKey
    }
})
my arguments for validate -  let receipt = {
                            data: req.body.receipt.receipt,
                            signature: req.body.receipt.signature
                        }
                        let credentials = {
                            clientId: androidPass.googleClientID,
                            clientSecret: androidPass.googleClientSecret,
                            refreshToken: androidPass.googleRefToken
                        }

I try validate it by  iap.validateOnce(receipt, credentials ) and have error like - Error: Missing Package Name.

What might be wrong?

**Comment by voltrue2** [comment]
Hello
  

  
Please read the documentation on the receipt object structure for Google. I believe the object structure you have there is not correct.
  

  
Cheers
  

  
  

  
  
>

**Comment by voltrue2** [comment]
Closing for no response
