### ISSUE TITLE
Is there any Plans for other purchase?

### ISSUE THREAD

**Issue by wade0317** [voltrue2/in-app-purchase#230]
Hi guys, is there any plans for other purchase?

such as:  paypal ,  alipay，wechatpay，stripe .

**Comment by voltrue2** [comment]
Hello
  

  
At the moment there is no plan for implemented any of those mentioned as I haven’t the experience of using any of those services in the backend.
  

  
Also this package is a receipt valudation. I think it would make more sense to create another library for it.
  

  
Best Regards   
  

  
  

  
  
>
