### ISSUE TITLE
No expirationDate field in the getPurchaseData response when testing subscription using test account for Android

### ISSUE THREAD

**Issue by jsitu** [voltrue2/in-app-purchase#234]
Quick question, when I send the receipt and signature from a test account to validate the google play subscription, I got the following response:
```
[
    {
        "orderId": "GPA.3318-2444-1952-27921",
        "packageName": "com.jstudio.dealcrunch",
        "productId": "dealcrunch.membership.gold.monthly",
        "purchaseTime": 1546683717359,
        "purchaseState": 0,
        "purchaseToken": "ebjfgjgegcbhkgkpdagjfebj.AO-J1OwEDeVafnn6JLV0V6DlOCZTF0tP0WstVf4ch0AQ_YmMGWcfk2ClUMQGT7qgbAlPITPJVrvHcM1hOr8nTtUN7Bq2-pD7nLaGd_z3lKmy_fAGYUarHsOmhL_RR4iMpQzsUfC2_1q3KhTmZzW5daPK_lFsL7BqBw",
        "autoRenewing": true,
        "status": 0,
        "service": "google",
        "transactionId": "ebjfgjgegcbhkgkpdagjfebj.AO-J1OwEDeVafnn6JLV0V6DlOCZTF0tP0WstVf4ch0AQ_YmMGWcfk2ClUMQGT7qgbAlPITPJVrvHcM1hOr8nTtUN7Bq2-pD7nLaGd_z3lKmy_fAGYUarHsOmhL_RR4iMpQzsUfC2_1q3KhTmZzW5daPK_lFsL7BqBw",
        "purchaseDate": 1546683717359,
        "quantity": 1
    }
]
```
I don't see anything related to expirationDate, how can I tell if a subscription is expired or cancelled in this case? Is it by design for test account or I am doing something wrong?

Also if I have `googleAccToken` and `googleRefToken` configured, the response will always return as empty or null for `getPurchaseData` response. Help needed, thanks in advanced.

**Comment by voltrue2** [comment]
Hello?

How are you validating your receipts? It looks like the library does not know your validating a subscription receipts

**Comment by jsitu** [comment]
@voltrue2 Here are the steps I took to validate the Android subscription:
1. Call `restorePurchase` from https://github.com/AlexDisler/cordova-plugin-inapppurchase
2. Get the receipt and signature from the response array
3. Setup receipt validation on the backend with such config
```
iap.config({
    googlePublicKeyStrLive: <key>,
    googleClientID: <clientID>,
    googleClientSecret: <clientSecret>
  });
```
4. Use your example code for the remaining part like this:
```
iap.setup((error) => {
    if (error) {
      res.send(error);
    }
    iap.validate(receipt, (e, response) => {
      if (e) {
        res.send(e);
      }
      if (iap.isValidated(response)) {
        res.send(purchaseData);
      }
    });
  });
```

Then what I got from the response is the validated receipt but doesn't have `expirationDate` on it. If I added `googleAccToken` and `googleRefToken` into the config, the response will always be an empty object (no error).

**Comment by jsitu** [comment]
@voltrue2 you rocked, that works! 👍

**Comment by voltrue2** [comment]
Awesome!   
  

  
  

  
  
>
