### ISSUE TITLE
Why is that the type of validation error is  "String", and not an instance of "Error"?

### ISSUE THREAD

**Issue by nushydude** [voltrue2/in-app-purchase#238]
Thanks for this package. I'm currently testing the latest version (1.10.8) on nodejs version 11.6.

I'm trying to extract the **reason** for an Android subscription purchase validation failure (i.e. network down or malformed purchaseToken) and communicate it back to the client. Was thinking that I could do something like: 

```
export async function validateAndStoreAndroidSubscription(root, { input }, ctx) {
  try {
    await iap.setup();

    const purchaseData = await iap
      .validate({ ...input, subscription: true })
      .then(iap.getPurchaseData);

    const subscription = await storeAndroidSubscription(purchaseData);

    return {
      error: null,
      subscription
    };
  } catch (error) {
    if (error.message === "The purchase token was not found") {
      return {
        error: createInvalidSubscriptionError(),
        subscription: null,
      };
    }

    if (error.message === "SOME_OTHER_MESSAGE_USED_FOR_DETERMINING_NETWORK_ERROR") {
      return {
        error: createServiceUnavailableError(),
        subscription: null,
      };
    }

    return {
      error: createServerError(error),
      subscription: null,
    };
  }
}
```

But `error.message` shows up as undefined. When I dug in deeper, I found out that the `error` is not an instance of `Error`, but is a `string`? Doesn't make any sense to me.

Is there a correct way to extract the error message?

Thanks

**Comment by voltrue2** [comment]
Hello,
At the moment the error you will catch is indeed a stringified object that "contains" error message.
I think there was a reason behind this, but unfortunately I cannot remember why.
I will have a look at it more closely, but in the meantime, you would check the stringified value for error message.

Cheers

**Comment by nushydude** [comment]
Alright. Like to know why it's stringified. Let us know if you would recall the reason.
