### ISSUE TITLE
Why is isValidated() helper function required?

### ISSUE THREAD

**Issue by nushydude** [voltrue2/in-app-purchase#239]
My understanding is that if the receipt/purchase token is invalid or if there is any error with the validation pipeline, iap.validate() will throw.

If that is the case, what's the purpose of `iap.isValidated()` helper? If `iap.validate()` doesn't throw, doesn't it mean it is valid? 

Are there any cases where it does not throw for invalid receipts?

**Comment by voltrue2** [comment]
Hello
  

  
This function is a legacy. Way back when the validation was behaving differently.
  

  
Cheers
  

  
  

  
  
>

**Comment by nushydude** [comment]
Perfect. Thanks.
