### ISSUE TITLE
googlePublicKeyStrSandbox Not Working (v0.5.3)

### ISSUE THREAD

**Issue by javierfdr** [voltrue2/in-app-purchase#24]
Hello,
When you set the public key directly as String, the library does not parse it well and gives the **missing public key** error.

My configuration is this:

```
  iap.config({
    applePassword: "66b24c8189d249889d454e65377d23b3",
    sandbox: true,
    googlePublicKeyStrSandBox: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtE8Y5ZYRwrHc6RJ5HGLampXt0jL3kNaZKZN2/KxloC4HuWFTFufmOjAefjogv+934Hvlmq04YQcEIh1wtqVk2WmwWvpWQK18FxBM45LksaE5S0kkzNQcWA0vjlqtZwQqlQg5ngB+xOyNojsfhGBdbLB+5s6NmSLsFfzgW29/tLxPHfewzEgFLmJ4PSRZo9ObPnLowYlZ7yDEaS6AIu739OnAwdU9qVWOo++TBLoLJ6+bT5fPMMSteZFfaEp+3QBM+qdNnnJ8zYMVHIYnD77GLBT08xLUiO8FnSEZZC5GAmYFmiJN8NKGMnt+bxy6+hhdcGatoUnMzzmSHvTjV3j1XQIDAQAB"
  });
```

When debugging the library I found this:

At in-app-purchase/lib/google.js, at configuration in line 59,

It can be seen that it is not entering in this if:

```
if (config && (config.googlePublicKeyStrSandbox || config.googlePublicKeyStrLive)) {
```

At that moment the value of **config** variable is:

```
{ googlePublicKeyStrSandBox: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtE8Y5ZYRwrHc6RJ5HGLampXt0jL3kNaZKZN2/KxloC4HuWFTFufmOjAefjogv+934Hvlmq04YQcEIh1wtqVk2WmwWvpWQK18FxBM45LksaE5S0kkzNQcWA0vjlqtZwQqlQg5ngB+xOyNojsfhGBdbLB+5s6NmSLsFfzgW29/tLxPHfewzEgFLmJ4PSRZo9ObPnLowYlZ7yDEaS6AIu739OnAwdU9qVWOo++TBLoLJ6+bT5fPMMSteZFfaEp+3QBM+qdNnnJ8zYMVHIYnD77GLBT08xLUiO8FnSEZZC5GAmYFmiJN8NKGMnt+bxy6+hhdcGatoUnMzzmSHvTjV3j1XQIDAQAB' }
```

So definitely it has been read but somehow config.googlePublicKeyStrSandbox outputs **undefined**

**Comment by voltrue2** [comment]
Hi, thank you for reaching out.
May I assume that you are looking at the latest version of this module from npm? 
The latest version should be 0.5.3

OK now that is out of the way, I will have a look at the code with your example. I should be able to get back to you within a day or so.

Now the reason behind that confusing logic is that you don't have to tell the module if you are on production or not. The module simply tries all.
But as you mentioned the error might be a little too confusing. I'll have a look to see if I can improve that.

**Comment by voltrue2** [comment]
Hi l looked at the code and your example.
Looks like your example has "googlePublicKeyStrSandBox", but it actually has to be "googlePublicKeyStrSandbox".

Could you try and see if this fixes your issue?

I will continue considering the possibility of improving the error handling.

Thanks!

**Comment by javierfdr** [comment]
Oh you are right, it has to be Sandbox (without the capital B in box). I finally used the reading from a file approach, but fixing this it should work.

Please see that in the example in the README you write this:

```
var iap = require('in-app-purchase');
iap.config({
    googlePublicKeyStrSandBox: publicKeySandboxString,
    googlePublicKeyStrLive: publicKeyLiveString
});
//... proceed with the rest of your code here
```

Here you have SandBox instead of Sandbox. The googlePublicKeyStrLive is ok.
If possible please correct this at the README to avoid confusions.

And thanks for the great Lib!

**Comment by voltrue2** [comment]
Thank you for pointing that out.

README.md fixed
