### ISSUE TITLE
[google] add data field when check fail

### ISSUE THREAD

**Issue by firstguo** [voltrue2/in-app-purchase#241]
when google check failure, the error message is drop.
![image](https://user-images.githubusercontent.com/3937038/52114872-2b737b00-2648-11e9-8332-eb3dfa7a39a9.png)

what about add data field in error information like this.
![image](https://user-images.githubusercontent.com/3937038/52114976-68d80880-2648-11e9-82da-0311daa4a8ea.png)

**Comment by voltrue2** [comment]
fixed: 8efacf428764de89bb8de55cf4bfa7b37dac07e1

**Comment by firstguo** [comment]
thanks

**Comment by firstguo** [comment]
![image](https://user-images.githubusercontent.com/3937038/52696993-614f2280-2fab-11e9-9a1a-6ec067fb947d.png)

/lib/google.js, in line 282:  
when data is  as follow,  loss the error info 
![image](https://user-images.githubusercontent.com/3937038/52697132-c0149c00-2fab-11e9-9ffa-bfd74ada8d65.png)
