### ISSUE TITLE
loss error info in google-play

### ISSUE THREAD

**Issue by firstguo** [voltrue2/in-app-purchase#243]
![image](https://user-images.githubusercontent.com/3937038/52696993-614f2280-2fab-11e9-9a1a-6ec067fb947d.png)

/lib/google.js, in line 282:  
when data is  as follow,  loss the error info 
![image](https://user-images.githubusercontent.com/3937038/52697132-c0149c00-2fab-11e9-9ffa-bfd74ada8d65.png)

_Originally posted by @firstguo in https://github.com/voltrue2/in-app-purchase/issues/241#issuecomment-463104191_

**Comment by voltrue2** [comment]
@firstguo

My apologies for getting back so late.
By “loss of error I info”, do you mean the receipt data that is supposed to be passed with an error?
If that is what you mean, I found a bug in createErrorData that the data of errorred receipt is returned always null.

I’ll fix this bug but please let me know this if the same issue you’re reporting it not.

Cheers!

**Comment by voltrue2** [comment]
Fix of the above mentioned: 13505ba2b7a80d0d2a9a1f2d32e2681da47cb034
Published npm version: `1.11.3`
