### ISSUE TITLE
[Solved] Sporadic errors when validating google receipts

### ISSUE THREAD

**Issue by Nalgmann** [voltrue2/in-app-purchase#245]
Hi. I write because I have seen a very annoying non-deterministic issue when I try to validate subscription receipts from PlayStore.

I use `googlePublicKeyStrLive` approach and sometimes the validation returns this:
```
 {"error":{},"status":1,"message":"client_id, client_secret, access_token and refres_token should be provided"}
```

Other times validation works like a charm. This is more common with recent and testing receipts. Production receipts are also affected.

I don't know why is this and it's really driving me nuts!

I actually use version `1.10.6`

Thanks

**Comment by voltrue2** [comment]
Hello,
  

  
In order to validate subscription receipts correctly, you need to use google API instead. I may need to update the documentation on this to clarify this point.
  

  
Let me know if this helps.
  

  
Cheers
  

  
  

  
  
>

**Comment by Nalgmann** [comment]
You mean, instead in-app-purchase? I use google API to get info about a subscription, but once validated via in-app-purchase

**Comment by voltrue2** [comment]
No. in-app-purchase module has that ability.
  
You simply feed the right configurations to it.
  
It’s on the documentation.
  

  
  
 https://github.com/voltrue2/in-app-purchase/blob/develop/README.md#how-to-use
  

  
Please have a look at googleServiceAccount in the documentation.
  

  

  
  
>

**Comment by Nalgmann** [comment]
I see the fields for google service account. Tried but throws me a new error: 

```
{\"error\":{},\"status\":1,\"message\":\"Missing Package Name\"}
```

I don't know where to put it. I tried inside `googleServiceAccount` object and outside at the moment of config

**Comment by voltrue2** [comment]
The receipts must follow the format shown below:
  

  
 https://github.com/voltrue2/in-app-purchase/blob/develop/README.md#google-play-using-google-service-account-with-unity-receipt
  

  
  

  
  
>

**Comment by Nalgmann** [comment]
Thanks a lot! I haven't noticed the requirements for service accounts. Specially because this hasn't been necessary. Just for clarity, I used format for google service account, not unity.

https://github.com/voltrue2/in-app-purchase/blob/develop/README.md#google-play-using-google-service-account

I use this approach in case the traditional method fails.

I repeat. Thanks a lot, and sorry the hassle.

**Comment by Nalgmann** [comment]
I'll close this issue.

**Comment by voltrue2** [comment]
No worries!   
  

  
Cheers
  

  
  

  
  
>
