### ISSUE TITLE
Amazon getPurchaseData always empty

### ISSUE THREAD

**Issue by mrpuzzler** [voltrue2/in-app-purchase#246]
Amazon getPurchaseData always empty IF:

var options = {
 ignoreCanceled: true,
  ignoreExpired: true 
};
var purchaseData = iap.getPurchaseData(validatedData, options);

AND Amazon IAP which with cancelDate: null

This check at amazon2.js is wrong, as it does not check for null and should only process SUBSCRIPTIONS, but not CONSUMABLE

    if (options && options.ignoreExpired && purchase.cancelDate <= now) {
        return [];
    }

Suggest to check for purchase.cancelDate != null

**Comment by mrpuzzler** [comment]
This is how validatedData looks, and we get empty purchaseData for it.

Validation successful: { betaProduct: false,
  cancelDate: null,
  parentProductId: null,
  productId: 'mundus.coins.pack9',
  productType: 'CONSUMABLE',
  purchaseDate: 1552594408669,
  quantity: 1,
  receiptId: 'LONG STRING=:1:21',
  renewalDate: null,
  term: null,
  termSku: null,
  testTransaction: false,
  status: 0,
  service: 'amazon' }

**Comment by mrpuzzler** [comment]
Suggested fix is:

if (options && options.ignoreExpired && purchase.cancelDate && purchase.cancelDate <= now) {
    return [];
}

**Comment by voltrue2** [comment]
Here is the fix: 93ccad796e62d9e80d2eb4db8599a500506118a5

Thank you again for reporting the issue.

Cheers!

**Comment by mrpuzzler** [comment]
Great, thanks a lot.
