### ISSUE TITLE
Cannot tell whether a google store purchase is a test purchase

### ISSUE THREAD

**Issue by comtaler** [voltrue2/in-app-purchase#248]
When validating a receipt from Google store, the validatedData does not contain information about whether this is a test purchase or not.

On google store, we can specify licensed users, and whichever device is logged into the licensed account can make in app purchase without being charged. That messes up our analytics data. We need a way to tell the purchase is a test purchase.

According to this documentation:
https://developers.google.com/android-publisher/api-ref/purchases/products
we should be able to tell when purchaseType = test

**Comment by voltrue2** [comment]
Hello
  

  
the library passes the validated receipt as is (getPurchaseData changes the validated data).
  
If you do not have purchaseType in the validates data, according to the Google documentation, the purchase was made with the standard in-app billing flow.
  
PurchaseType: Quote “This field is only set if this purchase was not made using the standard in-app billing flow.   “
  

  
Cheers
  
  

  
>

**Comment by comtaler** [comment]
I think it's because I didn't enable google service account settings. However, when I enabled it, it says my receipt is missing packageName. I opened a separate issue: #249 

I will update this once #249 is resolved.

**Comment by comtaler** [comment]
The reason I am using google service for validating is to know whether it is a test purchase or not. Since it's an external service, there is a chance that it can go down or has temporary outage that would affect IAP, which is an essential part of our app. Is there a way to allow fallback to validate with public key if google service validation fails?

**Comment by voltrue2** [comment]
Hello,
  

  
There isn’t fallback like that at the moment, but I think it is a valid point. I will try to add fallback to public key validation if provided!
  

  
Cheers
  

  
  

  
  
>

**Comment by comtaler** [comment]
@voltrue2 I can get PurchaseType from the validated result now for test purchase. This one can be closed. Would you like to to open another feature request ticket regarding the fallback validation feature or just leave this one open?

**Comment by voltrue2** [comment]
I’ll close this issue. As for the fallback feature, I will need to think about it as it may cause unwanted behaviors when you are validating subscriptions.

**Comment by comtaler** [comment]
You can also leave this to the developers. I am ok to handle this on my own. But currently, once google service is set up, it will only use google service. If it can dynamically allow us to choose whether to use google service or local validation, that will work for me as well.
