### ISSUE TITLE
Unable to validate against Google service account

### ISSUE THREAD

**Issue by comtaler** [voltrue2/in-app-purchase#249]
With the receipt:
> {
>   data: '{"orderId":"test_order","packageName":"my_package_name","productId":"my_product_id","purchaseTime":1545424430852,"purchaseState":0,"purchaseToken":"some_token"}',
>   signature: 'some_signature'
> }

It works when validating with a public key. But when I enabled googleServiceAccount setting in the config, and calls iap.validate(receipt), it says packageName is missing.

**Comment by voltrue2** [comment]
Hello   
  

  
Please read the documentation:   https://github.com/voltrue2/in-app-purchase/blob/develop/README.md#google-play-using-google-service-account
  

  
The receipt format for Google service account is different.
  

  
Cheers
  

  
  

  
  
>

**Comment by comtaler** [comment]
I also tried that as well by passing data field as parsed json object from the original receipt. But It seems it failed to detect the proper service type from the receipt.

Can I know why we need to have a different receipt format for using google service account? Why can't it take the original receipt and use the data field as the receipt for google service?

**Comment by voltrue2** [comment]
Hello
  

  
The format is as follows:
  

  
  
  { packageName: 'The packge name of the item purchased',   productId: 'The product ID of the item purchased', purchaseToken: 'PurchaseToken of the receipt from Google', subscription: true/false // if the receipt is a subscription, then true }   
  
 Cheers
    

  
  

  
  
>

**Comment by comtaler** [comment]
Thanks for the quick reply. I understand that the receipt format is different when using google service for validation, but for both using or not using google service:
```
const stringReceipt = '{"data":"{\"orderId\":\"test_order\",\"packageName\":\"my_package_name\",\"productId\":\"my_product_id\",\"purchaseTime\":1545424430852,\"purchaseState\":0,\"purchaseToken\":\"some_token\"}","signature":"some_signature"}';
iap.validate(stringReceipt);
```
or
```
const objReceipt = { packageName: 'my_package_name',   productId: 'my_product_id', purchaseToken: 'some_token', subscription: false };
iap.validate(objReceipt);
```

They both fail. The second one tries to validate the receipt through Amazon service instead of Google service.

**Comment by voltrue2** [comment]
Hello
  

  
I assume you have the proper configurations for using Google service account? I mean the configurations for this library?
  

  

  
  
If both configurations and receipt format are correct, this is the first time I heard about any issue. I would like to track it down if possible.
  

  
Cheers   
  
  
>

**Comment by comtaler** [comment]
Thanks for your reply. It was my mistake that I pass in string instead of object to the validate function. It works now by passing in an object instead. Please feel free to close the issue.

**Comment by voltrue2** [comment]
Awesome.   
  

  
  

  
  
>
