### ISSUE TITLE
failed to validate Windows purchase

### ISSUE THREAD

**Issue by klinkov** [voltrue2/in-app-purchase#25]
I got this error 
Error: failed to validate purchase: canonicalization algorithm 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315' is not supported

[test.txt](https://github.com/voltrue2/in-app-purchase/files/65523/test.txt)

**Comment by voltrue2** [comment]
Hi 

Thanks for reaching out.
Let me have a look at what you have here.

**Comment by voltrue2** [comment]
Hello

It seems the receipt you have is signed with http://www.w3.org/TR/2001/REC-xml-c14n-20010315 algorithm which happens to be something that I am not supporting currently. I will have to implement this feature. Are you in a hurry?

**Comment by voltrue2** [comment]
Could you explain how you generated this receipt that failed to validate?

**Comment by klinkov** [comment]
I got it from Windows Store

**Comment by voltrue2** [comment]
So you weren't using an emulator but a real windows phone?

**Comment by klinkov** [comment]
I solve this issue, update signed_xml and exclusive_canonicalization

[in-app-purchase.zip](https://github.com/voltrue2/in-app-purchase/files/66431/in-app-purchase.zip)

**Comment by voltrue2** [comment]
I see so you changed the sign algorithm.
Thanks for the update

**Comment by klinkov** [comment]
I got receipt on real device

**Comment by voltrue2** [comment]
Supported encryption for signed XML (Windows)

## Supported Algorithms

### Canonicalization and Transformation Algorithms

- Exclusive Canonicalization http://www.w3.org/2001/10/xml-exc-c14n#

- Exclusive Canonicalization with comments http://www.w3.org/2001/10/xml-exc-c14n#WithComments

- Enveloped Signature transform http://www.w3.org/2000/09/xmldsig#enveloped-signature

### Hashing Algorithms

- SHA1 digests http://www.w3.org/2000/09/xmldsig#sha1

- SHA256 digests http://www.w3.org/2001/04/xmlenc#sha256

- SHA512 digests http://www.w3.org/2001/04/xmlenc#sha512

### Signature Algorithms

- RSA-SHA1 http://www.w3.org/2000/09/xmldsig#rsa-sha1

- RSA-SHA256 http://www.w3.org/2001/04/xmldsig-more#rsa-sha256

- RSA-SHA512 http://www.w3.org/2001/04/xmldsig-more#rsa-sha512

- HMAC-SHA1 http://www.w3.org/2000/09/xmldsig#hmac-sha1
