### ISSUE TITLE
expires_date is before original_purchase_date?

### ISSUE THREAD

**Issue by cjroth** [voltrue2/in-app-purchase#255]
I'm getting this back from Apple for `latest_receipt_info` in sandbox environment:
```
{ quantity: '1',
       product_id: 'basicannual',
       transaction_id: '1000000525422468',
       original_transaction_id: '1000000518175040',
       purchase_date: '2019-04-26 09:17:18 Etc/GMT',
       purchase_date_ms: '1556270238000',
       purchase_date_pst: '2019-04-26 02:17:18 America/Los_Angeles',
       original_purchase_date: '2019-05-07 04:17:59 Etc/GMT',
       original_purchase_date_ms: '1557202679000',
       original_purchase_date_pst: '2019-05-06 21:17:59 America/Los_Angeles',
       expires_date: '2019-04-26 10:17:18 Etc/GMT',
       expires_date_ms: '1556273838000',
       expires_date_pst: '2019-04-26 03:17:18 America/Los_Angeles',
       web_order_line_item_id: '1000000044083511',
       is_trial_period: 'false',
       is_in_intro_offer_period: 'false' }
```

Notice that `original_purchase_date` is before `expires_date`. Am I crazy or is this a bug with Apple?

**Comment by voltrue2** [comment]
Hello,
I know that Apple's sandbox is not really well maintained... but this looks indeed odd.
When I look at `purchase_date_ms` and `expires_date_ms`, they seem to be correct.
It might actually be a bug in Apple sandbox.

Cheers

**Comment by cjroth** [comment]
Thanks for the reply. I figured as much... its reassuring that my code isn't broken, but holy shit Apple.

**Comment by mifi** [comment]
I'm having the same issue, glad to see it's not just me
