### ISSUE TITLE
This receipt is a production receipt, but it was sent to the sandbox service for verification.

### ISSUE THREAD

**Issue by bander-saeed94** [voltrue2/in-app-purchase#261]
I need your support.

This receipt is a production receipt, but it was sent to the sandbox service for verification.

**Comment by bander-saeed94** [comment]
constructor() {
    this.configObject = {
      requestDefaults: {
        /* Please refer to the request module documentation here: https://www.npmjs.com/package/request#requestoptions-callback */
      },

      /* Configurations for Apple */
      appleExcludeOldTransactions: true, // if you want to exclude old transaction, set this to true. Default is false
      applePassword: process.env.IAP_APPLE_PASSWORD, // this comes from iTunes Connect (You need this to valiate subscriptions)

      /* Configurations for Google Service Account validation: You can validate with just packageName, productId, and purchaseToken */
      // googleServiceAccount: {
      //     clientEmail: '<client email from Google API service account JSON key file>',
      //     privateKey: '<private key string from Google API service account JSON key file>'
      // },

      /* Configurations for Google Play */
      // googlePublicKeyPath: path.join(__dirname, '../keys/google_play'), // this is the path to the directory containing iap-sanbox/iap-live files
      googlePublicKeyStrSandBox: process.env.GOOGLE_IAB_PUBLICKEY_LIVE, // this is the google iap-sandbox public key string
      googlePublicKeyStrLive: process.env.GOOGLE_IAB_PUBLICKEY_LIVE, // this is the google iap-live public key string
      googleAccToken: process.env.GOOGLE_ACC_TOKEN, // optional, for Google Play subscriptions
      googleRefToken: process.env.GOOGLE_REF_TOKEN, // optional, for Google Play subscritions
      googleClientID: process.env.GOOGLE_CLIENT_ID, // optional, for Google Play subscriptions
      googleClientSecret: process.env.GOOGLE_CLIENT_SECRET, // optional, for Google Play subscriptions

      /* Configurations for Roku */
      // rokuApiKey: 'aaaa...', // this comes from Roku Developer Dashboard

      /* Configurations all platforms */
      test: process.env.SANDBOX_VERIFICATION, // For Apple and Googl Play to force Sandbox validation only
      verbose: true, // Output debug logs to stdout stream
    };
  }


i am setting SANDBOX_VERIFICATION=false

**Comment by voltrue2** [comment]
Hello,

I assume you are trying to validate Apple receipts?
Would you please give me the error log that you get so I have better understanding as to what is happening?

Cheers

**Comment by jaimegmx8** [comment]
I'm getting the same error, it was working fine during Apple Certification.

{"error":{"validatedData":{"sandbox":true,"status":21008,"message":"This receipt is a production receipt, but it was sent to the sandbox service for verification."}}

**Comment by voltrue2** [comment]
Hello,

This error comes from Apple server telling us that the receipt is a production receipt.
I need to know your setup in order to properly tell what is happening.

Cheers

**Comment by jaimegmx8** [comment]
While writing my answer I discovered that the environment variables weren't being parsed correctly, and we were actually setting test to true.

This looks like the same problem @bander-saeed94 was having.

Thank you @voltrue2.

**Comment by bander-saeed94** [comment]
> While writing my answer I discovered that the environment variables weren't being parsed correctly, and we were actually setting test to true.
> 
> This looks like the same problem @bander-saeed94 was having.
> 
> Thank you @voltrue2.

Yes, This is totally correct.

I was able to overcome it by:

```
test: process.env.SANDBOX_VERIFICATION == 'true' ? true: false,
```
