### ISSUE TITLE
multi accounts support

### ISSUE THREAD

**Issue by vincent-ogury** [voltrue2/in-app-purchase#266]
Hi,

Are they a way to handle multiple accounts configuration with your module?

As explained in the documentation and as I see in the code, you can only enter one configuration and validate payment against it.

If I have several account I can't do that:

```
iap.config({account1})
iap.setup({data1}).then(sucess).catch(err)
```
and
```
iap.config({account2})
iap.setup({data2}).then(sucess).catch(err)
```
in the same node process because "config" are shared on the module as a global static variable.

Something like:
```
iap.setup({conf}).then(instance => instance.validate(receip)).then(isValidated).catch(hasError)
```
Would be great to make it work with multiple accounts.

Or
something like:
```
IAP = require('in-app-purchase')

account1 = new IAP(configAccount1)
account1.validate(receipt).then(succeed).catch(err)

account2 = new IAP(configAccount2)
account2.validate(receipt).then(succeed).catch(err)
```

Vincent

**Comment by voltrue2** [comment]
Actually validateOnce() is exactly for that.

Cheers

**Comment by vincent-ogury** [comment]
Oh, yes sorry, I have missed that part:
https://github.com/voltrue2/in-app-purchase#validate-receipts-from-multiple-applications

Thanks, I go with it.
