### ISSUE TITLE
Timeout on Heroku before a purchase could be verified

### ISSUE THREAD

**Issue by logicware** [voltrue2/in-app-purchase#27]
Hi

I am getting timeout on Heroku before a purchase could be verified. Is there a way to configure timeout or handle the problem before Heroku times out in 30 secs?

**Comment by voltrue2** [comment]
Hello,

Thank you for reaching out.
At the moment there is no way to set custom timeout, but it makes sense to have such an option.
I will look into this. 
If you have any questions, please do let me know.

Cheers

**Comment by voltrue2** [comment]
Actually, if you are talking about iOS, you can set the custom timeout by:

```
iap.config({
  defaultRequests: {
    timeout: <timeout in miliseconds>
  }
});
```

**Comment by voltrue2** [comment]
It is written here: https://github.com/voltrue2/in-app-purchase#http-request-configuration

Please let me know if you have more questions or issues.

Thank you for reaching out.
