### ISSUE TITLE
<Google> Failed: malformed receipt

### ISSUE THREAD

**Issue by kodekq** [voltrue2/in-app-purchase#274]
Hello. I have a problem here. When I try to verify json, I get an error (<Google> Failed: malformed receipt), but if the received json is output to the log, copy and paste it onto the web service (http://iap.gracenode.org/), then it passes verification without any problems and there are no errors. In this situation, I do not even know which side to look for the problem.

**Comment by kodekq** [comment]
I figured out, it was necessary to get the resulting json through JSON.parse

**Comment by famictech2000** [comment]
Can you please elaborate the solution? ow do you get the info through JSON.parse?
