### ISSUE TITLE
qs dependency is vulnerable

### ISSUE THREAD

**Issue by jasonfma** [voltrue2/in-app-purchase#28]
Running nsp check yields a DOS vulnerability in qs dependency.

Path: in-app-purchase@0.5.5 > request@2.33.0 > qs@0.6.6 

We were able to use shrinkwrap to get around this and update the qs dependecy but would like to see the update happen here so we can use the library without modifications.

**Comment by voltrue2** [comment]
Hi

Thank you for reaching out and this issue is definitely important.
I'll have a look at it and update the module asap.

Cheers

Nobu

**Comment by voltrue2** [comment]
I did a quick search and updated request module's version to update qs module to 5.2.0 from 0.6.6.
This should remove the vulnerability you mentioned from the library.

Thank you for pointing this out.

Once I get a response back from you I will update npm. The new version would be 0.6.0

**Comment by jasonfma** [comment]
Nice thanks for the quick turn around!
