### ISSUE TITLE
Error: Missing public key

### ISSUE THREAD

**Issue by 92Harsha** [voltrue2/in-app-purchase#293]
let receipt = {
        "data":  '{"orderId":"GPA.3688-7453-9084-04836","packageName":"com.myapp","productId":"com.myapp.coins.10coins","purchaseTime":15724436038097,"purchaseState":0,"purchaseToken":"edgbpfkacopakokjllfoohgg.AO-J1Ow2MCW-baqvROp-IvUzbyMBjJefAe9b34f3w"}',
        "signature": MYSIGNATUREKEY
      }

    const response = await iap.validate(receipt);
    iap.setup(async function(){
      if (iap.isValidated(response)) {
        const purchase = await getPurchaseData(response);
      }
    }

i am getting this error message:
ERROR:
[VERBOSE] <Google> Try validate against live public key: undefined
[VERBOSE] <Google> Failed against sandbox public key: Error: missing public key
"{\"error\":{},\"status\":1,\"message\":\"missing public key\"}"

**Comment by chr4ss1** [comment]
have you set GOOGLE_IAB_PUBLICKEY_LIVE and GOOGLE_IAB_PUBLICKEY_SANDBOX environment variables that you get from developer.android.com -> google play console?
