### ISSUE TITLE
LICENSE Policy

### ISSUE THREAD

**Issue by roblav96** [voltrue2/in-app-purchase#32]
I'm a bit confused as to what your license policy states.

I'm familiar with the MIT, but that's about it. Am I able to use this project in a commercial product I'm selling to verify my in app purchases?

**Comment by voltrue2** [comment]
Hello

Yes you may use this module in a commercial product. I only ask that the project being properly acknowledged.

Best

-Nobuyori

**Comment by roblav96** [comment]
Ah! No problem at all! I have a specific page just for that. Do you have a logo or media you'd like for me to put?

**Comment by roblav96** [comment]
Any plans to implement promises? I'm going to try bluebirds promisify

**Comment by voltrue2** [comment]
Hello Ron,

Thanks for reaching out.
I don't have a logo at the moment. If you don't mind mentioning my module and name somewhere in your project(s) would be good enough for me :-)

As for promises, I am working on that right now.
I'm a little busy with other projects right now, but I'm planning on releasing the promise version of the module in 2 months or so.

I'm always open to feedbacks and thoughts!

Best

-Nobuyori

**Comment by roblav96** [comment]
This works wonders!
```javascript
var iap = require( 'in-app-purchase' )
iap.Pvalidate = Promise.promisify( iap.validate )
iap.config( {
	applePassword: "", // this comes from iTunes Connect
	googlePublicKeyPath: "" // this is the path to the directory containing iap-sanbox/iap-live files
} )
iap.setup()



module.exports = function ( req, res, next ) {

	req.that = {
		data: _.pick( req.json, [ 'recipt' ] ),
		xid: req.xid
	}

	Promise.resolve().bind( req.that ).then( function () {

		if ( _.isInvalidUndefined( this.data, [ 'recipt' ] ) ) {
			throw new restify.errors.InternalServerError( 'isInvalidUndefined!' )
		}

		return iap.Pvalidate( iap.APPLE, this.data.recipt )

	} ).then( function ( response ) {

		if ( !iap.isValidated( response ) ) {
			throw new restify.errors.BadRequestError( 'Invalid purchase recipt!!!' )
		}

		this.recipt = _.last( iap.getPurchaseData( response, {
			ignoreExpired: true
		} ) )

		if ( _.isUndefined( this.recipt.expirationDate ) ) {
			throw new restify.errors.BadRequestError( 'Invalid purchase recipt!!!' )
		}

		return r.table( 'users' ).get( this.xid ).update( {
			premium: this.recipt.expirationDate
		} )

	} ).then( function () {

		return redis.hset( 'tok:' + this.xid, 'prm', this.recipt.expirationDate )

	} ).then( function () {

		res.send( {
			stamp: this.recipt.expirationDate
		} )
		return next()

	} ).catch( restify.errors.BadRequestError, function ( err ) {
		res.send( {
			err: true,
			msg: err.message
		} )
		return next()
	} ).catch( restify.errors.InternalServerError, function ( err ) {
		return next( err )
	} ).catch( function ( err ) {
		return next( new restify.errors.InternalServerError( err ) )
	} )

}
```

Promisify works like a charm!

**Comment by voltrue2** [comment]
Awesome!

Thanks for the snippet. I just need to find the time to do this :-)

**Comment by roblav96** [comment]
No problem man!
