### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by Oakshiro** [voltrue2/in-app-purchase#4]
Please, update your documentation, you have several errors on it related to Google in app purchases configuration

In the first place, the environment variable should be GOOGLE_IAB_PUBLICKEY_SANDBOX and GOOGLE_IAB_PUBLICKEY_LIVE, NOT GOOGLE_IAB_PUBLIC_SANDBOX and GOOGLE_IAB_PUBLIC_LIVE

In the second place, the api keys as string should be called publicKeyStrSandBox  and publicKeyStrLive instead of googlePublicKeyStrSandBox and googlePublicKeyStrLive

Thanks

**Comment by voltrue2** [comment]
My bad. Thank you for pointing that out.
Will update the documentation soon.

**Comment by voltrue2** [comment]
Documentation corrected: 72c888e216a574315fdbc675a75a9ccbc1af17b7
