### ISSUE TITLE
What is in googleReceipt object?

### ISSUE THREAD

**Issue by pluspingya** [voltrue2/in-app-purchase#5]
Hi Nobuyori,

I'm trying to use your module to verify IAP for android in my nodejs server.
Your module is clean and look very easy to use, I like it a lot.

But I have no idea what should be in googleReceipt object
```
{
    data: "{}",   <-- can you give example format of this stringified data
    signature: "" <-- this one I completely have no idea what it is, and where to get it from?
}
```

Can you please give more detail about googleReceipt object?

Thank you in advance.

**Comment by pluspingya** [comment]
I think I see it now http://developer.android.com/google/play/billing/billing_integrate.html

```
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) { 
   if (requestCode == 1001) {           
      int responseCode = data.getIntExtra("RESPONSE_CODE", 0);
      String purchaseData = data.getStringExtra("INAPP_PURCHASE_DATA"); // <<=== HERE
      String dataSignature = data.getStringExtra("INAPP_DATA_SIGNATURE"); // <<=== HERE
        
      if (resultCode == RESULT_OK) {
         try {
            JSONObject jo = new JSONObject(purchaseData);
            String sku = jo.getString("productId");
            alert("You have bought the " + sku + ". Excellent choice, 
               adventurer!");
          }
          catch (JSONException e) {
             alert("Failed to parse purchase data.");
             e.printStackTrace();
          }
      }
   }
}
```

Please confirm If I am correct.

**Comment by voltrue2** [comment]
You should be getting something similar to the data below from Google when you start the purchase transaction:

{
	"data": "{
		\"orderId\":\"1222325443654533.3243423432432\",
		\"packageName\":\"you.app.package.name\",
		\"productId\": \"yourProdId\",
		\"purchaseTime\":1385366117073,
		\"purchaseState\":0,
		\"purchaseToken\":\"ffdsdgfdgfgfdgfdkhc.AO-J1OzchOueyJFGFDPGfdgspoWYWKp4lbu93Uk4RXjjSk_-OtzEzoghvqwmmYWbpVsd1jwtXPWS1G2WBwrAa9aDU5GMLbRJgz8B6d10UJipBDzOTjtx4gdN8\"
	},
	"signature":"EZLsGilci4RY59venVX93SHmfHZqLLDi0VCsuHmrvJhlmVCQleJzvgHTuQgoBTi2RrjTVPUyxM9NP3dYuF5fqti1rDwMw0TK/rCG7HdSAwOaKgLxKszoGW7GdhylKPexRvn/o2VhJ9r22MuT4kdkxIG5X5mFE1ViqFYVgAZ9v+q5nKWz7KZ+PwTmWuqAezDX91qHHVdKr3M6LWV9bdT1zdC3nhyWkPWaDvL8fB9ZdIm5U+ajIK3S+5K4sdsfdfdaUIUIUUIOUOIFISodsaPDosDIFDSbNYenEmBnonP72LycMrG4PMVieHCdT0/fhbwUOLQT+Xo7CA1kUr+2BAAAfdSjYlYX8bKw=="
}

As you can see, you have data and signature. You need to send those to the server and validate.
