### ISSUE TITLE
Failed to validate purchase in Android

### ISSUE THREAD

**Issue by ContinuousExcellence** [voltrue2/in-app-purchase#51]
I put my receipt and signature in database. And then I took both from database and android public key from play developer console. 
Using your module, on nodejs code I created receipt to validate using below code:

var receipt  = { data: JSON.stringify(receipt_val).replace(/\//g, '\/'), signature:iap_response[0].result[0].signature};

Below is Receipt:

var receipt= { data: '{"packageName":"com.utillix.utillixapp1","productId":"praveen_test","purchaseTime":146
3582360560,"purchaseState":"0","purchaseToken":"ohdbahlifnbfoelidfknfakp.AO-J1OxdAXy9EKF7uJT8Gg
g9YUcCvx-Lk7_zZFc4s9eLijoBPvv_uG3i5WDsb8TDIjS6-U-P1Qg-oFMDD7BhzdzXpYSlwld5mkSRr6moW8nG_I4D7TNV1
paMGM2esWumQWG-4tbcnsQo","autoRenewing":false}',
  signature: 'UhkS1bqFWD+UK3/3TnQ5/66YnW91FCe0hnSQtqegXb0rGPkAUzpmGq/P/Bh9nD9SE9Cvm22k/VBeI06hc
adlusplA4mwtXt9UN9xiSNOSmTnPhi4/NtZdDCFo3nGNrmL3UftEKdoHfAMvQZGUJ9rJGraI7kVku3etEAG16WY2i3Ymg8Z
fMD3c0bbgla7zmCKNc/jlvOFRieUxGGGiGyzyvH+HOLHijNZzalqwDc11FfFVnS6estETKj3YvZ+lbR9Dk/bHBZ1Zbme5lm
sgTIM9IR4QYSxXnKpvu64MSjcAwiyjgEonxJR8HNFvHDVX2EvVVCHDEi0qXIs48GjLazALQ==' }

Below is our Android Public Key

MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqNUCAUHQltDpsrsos+Ma
jFU3mgffZ8ir6uK/kgkm04ALUgaT1zQsfSnEaHuvjbr96mpwJfZ4N5RWmyB1tHfh
zAvHPMTs+IB2rdReMFZ1cc4C3ZVqSf7ADb+44DRuPkHwRg0hJ6+W8zCqh9ULH6WY
ywfPsWsqtmIoJ7QpUwlfwbMApLJwaf65uEHjh0S4JQH9His5OR76ozxB2sFb6BP/
d2mjdHkRjUXKPpI5/oLFWwGpfLkWg0Novozf2ZmwturdMxi/t3+tl3IRSaLYF4DW
nlsHwgH36UxC1/xWkHBSoPQuRGI6PddRzhdIWk5kbdiQXpbDVEraPhy0YPofda6t
YQIDAQAB

I put some console.log in validatePublicKey() on google.js to test. When it goes to verify function it returns false. and I always get error "Error: failed to validate purchase".
can I know where I am doing wrong?

**Comment by voltrue2** [comment]
Hello

It seems that either the receipt or the public key is incorrect. What the module is doing is simply validating the signed receipt as you can see.

.validate() can take data as an object also. You might want to try pass it as is instead of JSON.stringify it.

If that does not fix the issue, I am more than happy run some tests for you when I get a chance.

Best

**Comment by voltrue2** [comment]
Hello

Could you give me the receipt data w/o JSON.stringify and replace?

**Comment by ContinuousExcellence** [comment]
Hi,

I have already tried without JSON.stringify(). Its giving same proble,Also Please find below my receipt w/o JSON.stringify()

var receipt= { data:
   { packageName: 'com.utillix.utillixapp1',
     productId: 'praveen_test',
     purchaseTime: 1463582360560,
     purchaseState: '0',
     purchaseToken: 'ohdbahlifnbfoelidfknfakp.AO-J1OxdAXy9EKF7uJT8Ggg9YUcCvx-Lk7
_zZFc4s9eLijoBPvv_uG3i5WDsb8TDIjS6-U-P1Qg-oFMDD7BhzdzXpYSlwld5mkSRr6moW8nG_I4D7T
NV1paMGM2esWumQWG-4tbcnsQo',
     autoRenewing: false },
  signature: 'UhkS1bqFWD+UK3/3TnQ5/66YnW91FCe0hnSQtqegXb0rGPkAUzpmGq/P/Bh9nD9SE9
Cvm22k/VBeI06hcadlusplA4mwtXt9UN9xiSNOSmTnPhi4/NtZdDCFo3nGNrmL3UftEKdoHfAMvQZGUJ
9rJGraI7kVku3etEAG16WY2i3Ymg8ZfMD3c0bbgla7zmCKNc/jlvOFRieUxGGGiGyzyvH+HOLHijNZza
lqwDc11FfFVnS6estETKj3YvZ+lbR9Dk/bHBZ1Zbme5lmsgTIM9IR4QYSxXnKpvu64MSjcAwiyjgEonx
JR8HNFvHDVX2EvVVCHDEi0qXIs48GjLazALQ==' }

**Comment by ContinuousExcellence** [comment]
Also, Please find attached android public key

![iab key](https://cloud.githubusercontent.com/assets/7579244/15813925/5b9862f6-2be0-11e6-870a-c36311dcc997.png)

**Comment by ContinuousExcellence** [comment]
Thanks .I got issue. 

Although i need to use JSON.stringify() but when I was doing JSON.stringify(), value of purchaseState converted to string.So when I converted to int, It started working. 

 Thanks for your help and time.

**Comment by voltrue2** [comment]
I am glad it is working for you now.

Cheers

**Comment by glaydston** [comment]
Hi, Takahashi:

I have the same problem and I have tried all you could think. 

Could you help?

It's my receipt information:

``
[VERBOSE] <Google> Validate this: { data: 
   { orderId: 'GPA.1301-1377-8253-29193',
     packageName: 'com.mcontigo.inshake',
     productId: 'com.mcontigo.inshake.subscriptionar',
     purchaseState: 0,
     purchaseTime: 1463617019341,
     purchaseToken: 'iddnojaahbiakedmcodcihip.AO-J1OwlghdDQ5UC0f3u1NO8SVDBdECIUVVwbOB9EZ8_TKKsFZM3HTLFrhxRsuN5Q4u-kvWX8-t5LFDBDEG4W1tH_NDkmpFuBBnvBoWZhs63d14SjYa6o-PIh1P-Ku-zb4mPf37PO2HE9OJ0S3fQakXlNGE4_hhDBQ' },
  signature: 'FQdBCJexWF7hIlCeeHNhqgnyg+9Hr7YnX5Oh9nG99u/uN/UDuiTXFcK+XppzsV5vDhheGJh5aEqmn5Tdkpu2xjCBcEP67sDwcox4Bqp09yEmYo0yk2TCbhU0civw7jCFUhV6MaCOBnQg3NJd75qKTUw6zfw5DywZPaIYaO+9A3thnasWLtgPdVfVkQfrH7UXVZWbH3gGi/PaYe2n46eUBWxQ0qxzZgsHCFoJ9siyXn580n4MbF/ArF1C3UQ4Fcx/boa4UMGU9+IDtADYJgdNzH1V71990DaapJfkeOfghTWcKvuiwptWHfSun6eDlZ1fV+bQbf1CmHmjpxQyW5Sfaw==' }
``

And this is my Android Public Key:

``MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmgGOcIrdkEZu8pJ5QJLkWQLjUI4QHBXJSxFE72pIO9+yEaLpA5Vy8VIENIK9CoAEH0SEjJRpBxWvqzLEsZ5LUqsTc4GknBP0TQczMIx4l5xXgiVFRjqZjhNVs5lggK3I8a866bkNEagm+CW8P4xf5w+uXrFLtNjvslMCfLX3J9a32qs3Vbr6jd9yAra999XyHl9yXeyXt83tk928jtDnNNiJXt7stQ+e0srV46o7pDX8JMDI6yI4HMSs09LTpOb0fAyzgB9QXGglHqHyjKBVScYzaLFMNgCjIt4WZ6FD7Ymzo1+S++zy/rQTqiMQ8W7OrwuKa2yPQKriZu2bSDbL0QIDAQAB``


Thank for your time,

**Comment by voltrue2** [comment]
Hello,

I have tested with your receipt and public key given here.
I too was unable to validate.
The receipt seems to be fine and as far as I can tell the public key looks OK too.
All I can think of at this point is that we are using wrong public key for this receipt?

**Comment by glaydston** [comment]
Hi, Takahashi:

Thank you for your reply. 

My public key was wrong on Google Play and the app app is working fine currently.

I'll implement the subscription's validate. 

Thank for all,
