### ISSUE TITLE
Android validate method return {}

### ISSUE THREAD

**Issue by cmarqui** [voltrue2/in-app-purchase#57]
Hi,

We have a problem when we call .validate(), in the .config we pass the keys as strings and data formatted, both are correct because we have checked it in http://iap.gracenode.org/#validate-android and the format is the same like the file test/receipts/google. 

When we call to .setup() working correctly, but when call .validate() , it not enter in the function and print "{}" in mobile screen.

Do you know which is the problem?

Thanks in advance.

validationType = iap.GOOGLE;

iap.config({
          verbose: true,
        googlePublicKeyStrSandBox: SANDBOX_KEY_ANDROID,
        googlePublicKeyStrLive: PUBLIC_KEY_ANDROID
});

datajson = { "data": JSON.parse(request[0].receipt), "signature": request[0].signature };
datastring = JSON.stringify(datajson);
data = JSON.parse(datastring);

iap.setup(function (error) {
    if (error) {
          console.log(error);
    }
    else {
      iap.validate(validationType, data, function (err, response) {

```
      if (err) {
        console.log(err);
      }
      else {

        if (iap.isValidated(response)) {
        }
        else {
        }

      }
  });
}
```

});

**Comment by voltrue2** [comment]
Hello

Thanks for reaching out. So your problem is the callback of validate function not being called?

From the looks of it, your callback will not output anything unless there's an error b/c you are calling console.log in your error catching only.

Cheers

**Comment by cmarqui** [comment]
I discovered that error is in var validater = crypto.createVerify('SHA1'); (node_modules/in-app-purchases/lib/google.js line 381 ) from node code. I put try-catch and in the catch the error is "Unknown message digest".

Doy you have any idea?

Thank you so much.

**Comment by voltrue2** [comment]
Hello

It means the signature you are sending is incorrect.

Cheers

**Comment by cmarqui** [comment]
Hello,

I obtain the signature from RestorePurchases() method, how can this be incorrect?

I get the signature as follows:

{ "data": JSON.parse(request[0].receipt), "signature": request[0].signature };

And my signature is like : AaTdFoOdLr3HqPNbcJO2OqAMi1WVgOpVfTf.......DjVSAyAym7CshFLWuzliyvs+1ofhrdkQ==

Thank you

**Comment by voltrue2** [comment]
Closing as it does not seem to indicate bugs in the code.
