### ISSUE TITLE
Subscription Renewal?

### ISSUE THREAD

**Issue by DinnerForBreakfast** [voltrue2/in-app-purchase#59]
My Android app is sending the receipt for the subscription, the receipt is being validated as real, and the expiry time is being returned, but the expiry time is for the original receipt and not renewals, so isExpired() is returning true, even though the subscription has been renewed. Am I supposed to be sending a newer receipt?

**Comment by DinnerForBreakfast** [comment]
So it ended up being that Google was renewing the subscription but returning incorrect info on the API call, saying that the subscription was cancelled when it clearly wasn't. Cancelling and rebuying the subscription from the device fixed it.

**Comment by voltrue2** [comment]
Hello

Thank you for letting me know!

Cheers
