### ISSUE TITLE
Cancellation flag is not checked for Apple Receipts

### ISSUE THREAD

**Issue by Ltty** [voltrue2/in-app-purchase#61]
If a subscription is cancelled by the user or if the payment process fails a cancellation date is added to the receipt by the apple server. This flag is currently not checked by your implementation. So the module will return false when calling isExpired() even though the receipt was cancelled and is no longer valid.

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out!

Would you mind sharing the property that needs to be checked for this so I can implement it?

Cheers

**Comment by Ltty** [comment]
Here's the explanation taken from Apple's web site:
> Cancellation
> 
> A subscription is paid for in full when it’s purchased and can be refunded only by contacting Apple customer service. For example, if the user accidentally buys the wrong product, customer support can cancel the subscription and issue a refund. It’s not possible for customers to change their mind in the middle of a subscription period and decide they don’t want to pay for the rest of the subscription.
> 
> To check whether a purchase has been canceled, look for the Cancellation Date field in the receipt. If the field has a date in it, regardless of the subscription’s expiration date, the purchase has been canceled—treat a canceled receipt the same as if no purchase had ever been made.

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html

The field is named cancellation_date

**Comment by voltrue2** [comment]
Awesome!
Thank you. I'll implement this as soon as I get a chance.

Cheers

**Comment by voltrue2** [comment]
I have implemented this in develop branch I will be running more tests before merging it to master and publish on npm

**Comment by jshanman** [comment]
Any update on returning apple cancellation_date field? I see it referenced in the apple.js file but it does not appear to be used at all.

**Comment by voltrue2** [comment]
Hello

My apologies for the long wait.
I'll be looking into this shortly.

Cheers

**Comment by voltrue2** [comment]
cancellation_date field is now being read by the module.

Closing
