### ISSUE TITLE
Need to support Amazon IAP version 2.0

### ISSUE THREAD

**Issue by knadeau** [voltrue2/in-app-purchase#62]
Amazon has deprecated the API used by this package as of May 11, 2016.

Migration guide:
https://developer.amazon.com/public/apis/earn/in-app-purchasing/docs-v2/migrate-iapv1-apps-to-iapv2

**Comment by voltrue2** [comment]
Hello

Thanks for reaching out.
Great! I'll try to implement the new version of the Amazon API.

Cheers

**Comment by voltrue2** [comment]
I am trying to test the migrated API for this but it seems that Amazon now requires us to create a developer account or something to test this. 
Does anyone know of a good way to test the server API for this?

**Comment by JuliusNarvilas** [comment]
The only way to test seems to be creating a few "In-App Items", progressing them to "Live" state ("Live" state doesn't actually mean live, as in my experience it took several more hours before Amazon started to detect them) and create a test app under the "Live App Testing" tab of the app (for me, emails would only be sent out to testers that were added during the end of the test app publishing, for some reason).
The application has to be downloaded from the Amazon store to not run in sandbox mode from what I understand.

**Comment by JuliusNarvilas** [comment]
Haven't heard of ways to test Amazon IAP without an app on Amazon store.

**Comment by voltrue2** [comment]
Hello

Thank you for the info.
But Amazon is making it very difficult for me to maintain the server side only library like this :( it seems that I cannot have meaningful server-only unit tests..

**Comment by bmv0** [comment]
There is an unsafe JSON.parse in amazon2.js.
`SyntaxError: Unexpected token <
	at Object.parse (native)
	at Request._callback (/home/www/node_modules/in-app-purchase/lib/amazon2.js:159:18)
	at Request.self.callback (/home/www/node_modules/in-app-purchase/node_modules/request/request.js:186:22)
	at emitTwo (events.js:87:13)
	at Request.emit (events.js:172:7)
	at Request.<anonymous> (/home/www/node_modules/in-app-purchase/node_modules/request/request.js:1081:10)
	at emitOne (events.js:77:13)
	at Request.emit (events.js:169:7)
	at IncomingMessage.<anonymous> (/home/www/node_modules/in-app-purchase/node_modules/request/request.js:1001:12)
	at IncomingMessage.g (events.js:260:16)`

Unfortunately have no more context for this. I think amazon server can return here not only json, but also a html-page with an error.

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out and reporting this error. I'll look into this and have a fix ready as soon as I get the first chance.

Cheers

**Comment by voltrue2** [comment]
The issue has been addressed.
Thank you
