### ISSUE TITLE
Detect Trial subscription for Google In App Purchase.

### ISSUE THREAD

**Issue by igorescobar** [voltrue2/in-app-purchase#72]
Is there any way to detect if the current purchase it is about a trial subscription for google?
apple you can read the `is_trial_period` attribute but we don't have anything similar for Google.

Seems like the only way it is fetching this info via this endpoint:
https://developers.google.com/android-publisher/api-ref/inappproducts

Which would be a good increment for `in-app-purchase` if this is a only way we can figure this out.

**Comment by kayz1** [comment]
paymentState is not mapped from body (google.js line 263, 342)

`				data.purchaseState = body.purchaseState;
				data.autoRenewing = body.autoRenewing;
				data.expirationTime = body.expiryTimeMillis;`

**Comment by igorescobar** [comment]
Thanks @kayz1

**Comment by kayz1** [comment]
In version 1.4.1 it is mappet, just not in the case when access token is expired.
