### ISSUE TITLE
Android validation with play store api returns error validating non subscription product 

### ISSUE THREAD

**Issue by hankchinaski** [voltrue2/in-app-purchase#76]
Hi, I'm probably missing something here, I'm trying to validate both type of products subscription and consumable, but when I try to validate a consumable after I validate a subscription I get an error because the plugin tries to check the subscription state and fails (obviously). I am setting a different iap.config (after setting the "config" variable inside google.js to null) before iap.setup but I still get the error.
The plugin version is 1.1.10, thanks a lot in advance.

**Comment by voltrue2** [comment]
Hello thank you for reaching out.

The module does not expect you to call these functions more than once. There maybe something unexpected because of that. 

I'll have to look into it in more detail. In the meantime would you provide me with the error that you see?

Best regards

**Comment by hankchinaski** [comment]
Thanks for the reply!
Yeah, but if there are api credentials the module automatically check for subscription and I was trying to get both working (with no luck :) ). Anyway, the validation per se works but validate throws an error when trying to check the subscription state for non subscription products
here's my output after I made a successful subscription and trying to purchase a consumable product (wich is the same I get when I call one time iap.config with api credential and try to validate a non subscription product)  :

    [VERBOSE] <Google> Try validate against live public key: [my key]
    [VERBOSE] <Google> Validation against live public key successful: 
    { 
         packageName: 'com.bla.bla',
         productId: 'bla',
         purchaseTime: 1485438349209,
         purchaseState: 0,
         purchaseToken: [token],
         status: 0 
    }
    [VERBOSE] <Google> Get subscription info from https://www.googleapis.com/androidpublisher/v2/applications/com.bla.bla/purchases/subscriptions/bla/tokens/[token]
    [VERBOSE] <Google> Failed to get subscription info from https://www.googleapis.com/androidpublisher/v2/applications/com.bla.bla/purchases/subscriptions/month/tokens/[token] 
    null { error: { errors: [ [Object] ], code: 400, message: 'Invalid Value' } }
    [VERBOSE] <Google> Refresh Google token
    [VERBOSE] <Google> Successfully refreshed Google token: [token]
    [VERBOSE] <Google> Re-check subscription info: https://www.googleapis.com/androidpublisher/v2/applications/com.bla.bla/purchases/subscriptions/bla/tokens/[token]
    [VERBOSE] <Google> Re-check failed: https://www.googleapis.com/androidpublisher/v2/applications/com.bla.bla/purchases/subscriptions/bla/tokens/[token] 
    null { error: { errors: [ [Object] ], code: 400, message: 'Invalid Value' } }

**Comment by hankchinaski** [comment]
I'm sorry, I have totally missed #74 and that solves my issue :)
