### ISSUE TITLE
Google product validation support

### ISSUE THREAD

**Issue by tilutza** [voltrue2/in-app-purchase#78]
Hi,

At the moment I see that only subscriptions are able to be validated. According to https://developers.google.com/android-publisher/api-ref/purchases/products/get the products use other url. However, I was able to validate successfully a payment with the library by only changing the url in the checkSubscriptionStatus method (replacing /purchases/subscriptions/ with /purchases/products/)

I think a simple way to be able to add support on this, is to add a parameter in the receipt object that is passed through the validate method, something to be able to distinguish between a subscription and a purchase. After changing the url would be enought.

Do you think it is feasible to implement such a small feature ?

**Comment by voltrue2** [comment]
Hello

Thanks for reaching out. If it proves to be useful and others can also benefit from it, I would be happy to look at it. 

Would you be able to give me an example to show me what you did?

Best regards

**Comment by tilutza** [comment]
So, after the receipt is validated against the signature, you validate the purchasing too if it's still valid. This is done in the checkSubscriptionStatus where you construct the google url:

	var url = 'https://www.googleapis.com/androidpublisher/v2/applications/' + packageName + 
			'/purchases/subscription/' + subscriptionID + '/tokens/' + purchaseToken;

I don't have subscriptions, but i want to validate the purchasing of the product. This can be easily achieved by replacing the url with the following:
	var url = 'https://www.googleapis.com/androidpublisher/v2/applications/' + packageName + 
			'/purchases/products/' + subscriptionID + '/tokens/' + purchaseToken;

As you see, instead of subscription, you use products, and it simply works. 

I would suggest to rename the checkSubscriptionStatus in checkPurchasingStatus, and take another parameter (bool or whatever), to decide the construction or the url. This parameter needs to be supplier in the validate method (since you know if you want to validate a subscription or purchase).

As I said, I changed the URL manually to use products instead of subscriptions and it works without any change.

If you have other question, let me know

**Comment by voltrue2** [comment]
Hello,

My apologies on falling behind on these issues. I am trying to catch up.

Cheers

**Comment by voltrue2** [comment]
This is now possible by googleRefToken, googleClientID, and googleClientSecret in .config(...).

Closing
