### ISSUE TITLE
Production receipts unable to be validated (Android)

### ISSUE THREAD

**Issue by Arthien** [voltrue2/in-app-purchase#79]
We have been able to do tests purchases against our subscription product, but when we attempt to do a real purchase we are unable to validate it against this module. Our card is charged and we receive a receipt. We also have a local validation check as well that passes.

```{
"data":{
"packageName":"com.fanhero.floridacup",
"productId":"com.fanhero.subscription.monthly",
"purchaseTime":1486056847995,
"purchaseState":0,
"developerPayload":"474E6yrV6JDFWBobm7DrBu",
"orderId":"GPA.1331-4662-9366-45997",
"purchaseToken":"gjbemoolbkmdedknfodeibai.AO-J1OwpS4EPqxR72fPO2zfBe1IB4ZmCNZVNQwkBoGFmq3qLeT7JTyo_qHOlEYc1d-XYDZ74AT0gNqfKBHLqzU_JT3s5879W66ARA7EPF8W7c_SbwAfzT-GKICRMZHpjnc1JlICrj-aSYx0VeHU_0L813i3Q0LM32Q",
"autoRenewing":true
},
"signature":"RAzTtjQILmZQcCSvshaTq16kaOAYGOncRjKdnsra9fMr7w3kK8KuA9wptFZaZ4UKdw/i0M+8uPJhOCAU1DQ+AkDn/oq/HJOe3XBx3PhwyCFMtDPdvciZaHX1X1FaE7Fh+jFRwzIlbSDXl8g68R+A6ZLWyI8b2PRXrqSOGmz6ovAWynfDGs0SynsYO6Eev1ZG5kb++uOu/ow+VO+jHkjdQhQ3ZU6BFujWpBH2OEAqLvFuifCFg63v9omhTKcF7VoLEb7qQC/R2X5ynOI50qsZCHJ3EcDBEz+pKXJA8ABkonUVN3IFuEcmHOSqwAmFAwHxfeXscoPgGZ6a5SkeYCLgRw=="
}
```

`MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhl6BuxTHtotFWhYhrxuX64CU1b9Ao2xA8pLtRa08Rj2+XYlbqe+VK0FYQM2CRYljptikBWRJgCVCDleopx9z8eSb82DmlqBjyKd724fphA6sW1iRN9z9r6wQOKwVMLuc/NXzHO/S73TZBPxMwztPnWyRWYaPsmG3b3o6hRwNBhqForm68nK5bQNd66m6m2cIwLweuJ9hUPws0gv7G0ikpsrVU79IOPFyXiu0BO+Q3vybLONQapAIe78HDWosxffF2gEQAaeCitgJtYuRHfikJ25IMsVTyiiY3YEym0OKnmD9/pHTBFEv8wksE+wJnB+zJj1ETL6J10KC2BDJOgrCewIDAQAB`

Any help with this would be much appreciated

**Comment by murat-yuksel** [comment]
Same here, throws "failed to validate purchase"

**Comment by voltrue2** [comment]
Hello

Let me look into it. I have a hunch that there's something wrong with the receipts or something similar.

Cheers

**Comment by Arthien** [comment]
@voltrue2 Any idea why we are able to validate using google's example before sending to our API?
https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/app/src/main/java/com/example/android/trivialdrivesample/util/IabHelper.java

The api is only able to validate if there is no money involved. As soon as we take the user off the testing list, the API validation fails, but the local validation continues to pass. The only variable here is removing the user from the testing list.

**Comment by skotturi** [comment]
@Arthien are you able to catch expired android subscriptions ? 

I've the setup the Play Store API and confirming the test account in the play store that the sub is expired, when i run .validate( .getPurchaseData( .isExpired() ) ) 
I continually see the purchase as not expired. 

Just curious if your cancelled test subs are being caught correctly.

**Comment by priiduneemre** [comment]
@sktturi: I seem to have the same problem. Did you ever find a solution for this?

**Comment by priiduneemre** [comment]
Pro-tip to anyone else reading this: the `iap.getPurchaseData(response, {ignoreExpired: true});` shortcut doesn't work for Google Play (it only works for `iap.APPLE` and `iap.WINDOWS`). You can verify it yourself by inspecting the source code -- IMHO, this was not clear from the documentation.

To make sure that the expiration check is done for both `iap.GOOGLE` and `iap.APPLE`, you have to use the longer form described in the docs (_i.e._ calling `iap.isExpired(..)` manually in a `for` loop).

**Comment by voltrue2** [comment]
@Priidu Neemre

Thank you for sharing this and my solidifies for the lack of clarity in the doc.

Perhaps I should make ignoreExpired also valid for iOS?

**Comment by priiduneemre** [comment]
@voltrue2: Actually, the expiry check works for `iap.APPLE`, but not for `iap.GOOGLE` (I think you might have missed this in my comment). To answer your question -- I guess it would be nice if it worked uniformly for `iap.GOOGLE` as well. 

But if that's difficult to do, then IMHO it would also be fine to just add something like "For other platforms, see the `isExpired(..)` method" after the part in the documentation that describes the `ignoreExpired` option.

**Comment by k00k** [comment]
+1 to what @priiduneemre is saying. Would be great to be able to use `ignoreExpired` for Google and Amazon also.

**Comment by voltrue2** [comment]
Hello,

I am adding a link to a related topic here. I have updated the module to support Google Play subscription validation and `.isExpired()` now supports Android with this also.

I will continue to looking to supporting Amazon and Windows.

Cheers!

**Comment by alamboley** [comment]
Hey, just trying to validate IAP for Android too.. but I can't find Android iap-sandbox key. Do you know where I can grab it? I just have iap-live key.

**Comment by k00k** [comment]
@alamboley I believe you can just use the same key for both files.

**Comment by voltrue2** [comment]
Closing as it has presumably been solved
