### ISSUE TITLE
Is there a demo of how to use it in electron?

### ISSUE THREAD

**Issue by AndrewLang** [voltrue2/in-app-purchase#83]
Is there a demo or instruction of how to use it for electron and apple app store?

Thanks.

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out.

Now to answer your question, the moment there isn't one.

Now may I ask if you use Electron for all of your apps?
If people are using it for apps a lot, I might consider creating an example for it.

Best regards

**Comment by AndrewLang** [comment]
Thanks for your reply.

One more question, from apple's in-app purchase programming guide here [https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Introduction.html#//apple_ref/doc/uid/TP40008267], how can I retrieve my app's information from and send payment request to APP Store with this package?  I didn't find the API, if there is could you please give some code snippet?

Thanks.
