### ISSUE TITLE
failed to validate against google public key

### ISSUE THREAD

**Issue by xinyishen** [voltrue2/in-app-purchase#87]
Hi,
I am trying to validate a receipt. 
The message return is : <Google> Failed to validate against: public key.
And follow the error message: "errorMessage":"Error: failed to validate purchase
I am wonder what would be the reason? Is it something wrong with the key? Or is the data I sent in is in the wrong format?
Many Thanks!

**Comment by voltrue2** [comment]
Hello

There are two possibilities when you get the error. 
As you suggested there maybe something wrong with your public key or the receipt data.
 Please make sure that your receipt is escaped properly.

Best regards

**Comment by xinyishen** [comment]
Hi, 
Thank you so much for response!

Could you please take a look at the error data below and check if I did not escape the receipt properly? should I escape all the double quotes?

{"errorMessage":"Error: failed to validate purchase | MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt6VXV+w4XQ4gb2s04v/FOATpm3+wvb85DOKjW6NSJteuh50Oj0m+S+yeNq3htou0SCn6fluvvPfaEWAON5E2DK91zBlRSwrJie+hQAIIWtT22CEYX+OGTKni4GXfFRK6H/8+GLC3qM4HFJdH5Zsf87d+cgVbwPku/yvzW+fkcNSa6GyWXD64G4U15+5Dcc4dh+yDYk8VvND0LcMX1TACoVhCIfl7gTOhYflF/xSjnErVzzuKSsuFTYMyjqpa+/B6yyKzjl3KUgz2HbMDkpLtVV/F3nWMxCk7vIUJbtJywliTMvpSbWJ+StfbgAffcRk5YT6Cq10xm7qzq8TRmwIDAQAB | {\"data\":\"{\\\"purchaseToken\\\":\\\"jdakbaaagdnnagcofaon.AO-J1OxdO8T_HTGWBId5tt68U9L1K2vbS7po4_eV3HpGwrIOwN_dgNC3hJfmL-_BUJsg4u-yA4AxK6T6chGfcrb6WiaR1n1_mRvgCPpUBTFH2xfOq1h_095HqFGWInrqgYjE8rFj2jYE\\\",\\\"productId\\\":\\\"coins_1\\\",\\\"orderId\\\":\\\"GPA.w-2594-4554-86386\\\",\\\"purchaseTime\\\":1492924771095,\\\"packageName\\\":\\\"com.com1.com2\\\",\\\"developerPayload\\\":\\\"2a16-9888-464d-a3cc-d2a80f502fb7\\\",\\\"purchaseState\\\":0}\",\"signature\":\"vLX3zhiz3uqKw6pQXX/rZ4YP0eWszfhnlTWPbD3HwyqR53OiHZnqRnfOy2D6IFq6toiQDpL1GF940Vnlo2g8SM6gEhqZ/5IkbQeFtLWZw4Pyw3kjxUGkBcGHuUAF+gq7qQ9TPAdpRBuJ1GZg2k+y16dLUsA+/qEr0uYZg7R8VP6UYOEm7Wa2Vv27TNaD+m5V78Oz+LN5rojVbq5gLd+U714BAgQ1OxJVBLd3gkMFiHhbhXh5O9a1EtOURtyWg07n6kJ+ismcYgNMv6OeLHnqZ6Y6vDUVwWvfSPSMmgKF9cYZB0YVeOreUVQlu5cs6odYFYr9uytnezJeC9dlpg==\"}"}

Thank you!
