### ISSUE TITLE
Where I can get a receipt?

### ISSUE THREAD

**Issue by alexey-sh** [voltrue2/in-app-purchase#88]
Hi
Thanks for the library.
Where I can get a receipt for apple IAP?

**Comment by voltrue2** [comment]
You need to use iOS API to get your receipts from Apple

**Comment by alexey-sh** [comment]
hi @voltrue2 thanks for the response.
What if I'm using mac os app(electron) and want to add IAP?

**Comment by voltrue2** [comment]
Hello,

My apologies for the late response on this.
If your building an app for Mac OS and using Electron,
I do not think there are any APIs for in-app purchase as far as I am aware.
But this is like a few years ago though.

Best

**Comment by alexey-sh** [comment]
Thanks
