### ISSUE TITLE
expirationDate is 0 for a cancelled subscription

### ISSUE THREAD

**Issue by a-koka** [voltrue2/in-app-purchase#91]
I have a cancelled Apple subscription which is returning 0 for it's `expirationDate`. The response payload seems to have no information to help determine if a subscription is recurring or cancelled for Apple subscription. For Google purchases, the `autoRenewing` flag helps solve this problem.

Is there no information we can gather from Apple receipts to determine if a recurring subscription was cancelled?

**Comment by voltrue2** [comment]
Hello,
My apologies for getting back to you so late.
To determine if a subscription has been cancelled or not, you will need to check the field called `cancellation_date` in the payload of receipt validation.
For Apple documentation on this, please read here: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html

**Comment by a-koka** [comment]
Hi @voltrue2! No problem on the delay and thanks for the link. I don't see `cancellation_date` coming through in the response to `validate`. Would it appear only if a purchase was actually cancelled?

Although, this information is valuable, it doesn't address my problem. I should have explained better. I'm dealing with an active subscription which has been cancelled ie. the purchase is still valid but would not renew. Is there no way to detect this for iOS?

**Comment by gpinkham** [comment]
@a-koka I have been curious about that as well..   I have been assuming cancellation_date wouldn't show up until it was fully cancelled.. (ie: end of period)..      But now I'm beginning to wonder if the user cancelled today would the cancellation_date be today and expiration_date would be the end of the period..   kinda wish Apple had a real sandbox that actually allowed you to cancel and see this data.

**Comment by a-koka** [comment]
This just came in my mailbox a few days ago. Looks like Apple is addressing similar concerns by introducing new fields. We just need to provide these fields via the lib.

[https://itunespartner.apple.com/en/apps/news/45333106?sc_cid=NSL-AP-ENREC](https://itunespartner.apple.com/en/apps/news/45333106?sc_cid=NSL-AP-ENREC)

**Comment by voltrue2** [comment]
Thank you for the info.
I'll be updating the module with new fields soon :)

**Comment by voltrue2** [comment]
Hello

@a-koka Sorry it took me a while to get to this.
Please have a look at this commit: ca8ae978e31efc9dff1659e1b467f90337b1c240

With this, if a purchase has been cancelled, it treats it as expired.

Cheers!

**Comment by voltrue2** [comment]
Related to: https://github.com/voltrue2/in-app-purchase/issues/110

**Comment by voltrue2** [comment]
#114 should have fixed this issue.
