### ISSUE TITLE
Detect service by receipt

### ISSUE THREAD

**Issue by rzer** [voltrue2/in-app-purchase#92]
I think it will be very convinient to have a method such as validateAny(receipt, callback) or method detectService(receipt):[service const value] which you can use, for example like this:

iap.validate(iap.detectService(receipt), receipt, callback);

**Comment by voltrue2** [comment]
Hello,

Thanks for reaching out.
That's an interesting suggestion. I will look into it.

Cheers

**Comment by voltrue2** [comment]
Hello

I implemented this feature and published.

Thanks again for suggesting it!

**Comment by rzer** [comment]
Hi, wow it's cool) Big thanks for the great module!
