### ISSUE TITLE
Apple transactionId

### ISSUE THREAD

**Issue by raufdean** [voltrue2/in-app-purchase#93]
Hi,
In commit f76b872 the transaction id from the Apple receipt is converted to a float. The Apple specs state that this field should be a string. Our db schema is also expecting a string for this field.. Any reason why this should be converted to a number ?

https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411288-transactionidentifier

**Comment by voltrue2** [comment]
Hello,

Thank you for pointing this out.
Actually there's no reason for it. The parser currently looks at each value returned from Apple and it a value looks like a numeric value, it blindly converts it to a number.
I will correct this in my near future commit.

Cheers

**Comment by voltrue2** [comment]
The was a bug in my previous commit.
Here is the fix for it: 185403e084f44fd34f4e161009c282107f3903f8
Also I published the new version on npm with the fix: v1.4.2

**Comment by raufdean** [comment]
Thanks! I'll try out the new version and let you know if I find any issues..

**Comment by voltrue2** [comment]
Assuming it's been fixed, I'm closing this. :)
