### ISSUE TITLE
Google paymentState

### ISSUE THREAD

**Issue by kayz1** [voltrue2/in-app-purchase#94]
Can you map (forward) the paymentState from response body to data in the lib?

google.js (lines 263 and 342)
`data.purchaseState = body.purchaseState;
data.autoRenewing = body.autoRenewing;
data.expirationTime = body.expiryTimeMillis;
`

Add here 

`data.data.paymentState = body.paymentState;`

**Comment by voltrue2** [comment]
Hello
Thank you for reaching out. I have implemented this in the following commit: bd95925b5116cac8ce5fb64b88038acccee98d7a

I will be publishing this version soon.

Cheers!

**Comment by voltrue2** [comment]
v1.4.1 published

Cheers

**Comment by kayz1** [comment]
That was fast. But assignment is missing in **recheck** function (when token is expired in getSubInfo).
