### ISSUE TITLE
google validate for refunds

### ISSUE THREAD

**Issue by kelchy** [voltrue2/in-app-purchase#96]
I notice this project does not connect to google whenever a verification happens. it validates based on encryption keys offline only. this will not work for example a customer applied for a refund a few hours after. any plans to address this?

**Comment by voltrue2** [comment]
I might look into it if there are enough requests for this feature.
I just haven't had any so far.
So I would like to start with your opinion on it.
How critical/useful do you think it would be?

**Comment by voltrue2** [comment]
Hello,

With this update, you will have cancelation date in your validation response to check against: 244fea6cc9711a506cc11a65b9acfd5fa8e2d222

**Comment by voltrue2** [comment]
The module with this update is version `1.6.0`.

**Comment by kelchy** [comment]
thanks

Kelvin Chua

On Tue, Aug 1, 2017 at 7:03 AM, Nobuyori Takahashi <notifications@github.com

**Comment by voltrue2** [comment]
Cheers!
